### ISSUE TITLE
[Bug] issue with the "..." username mention

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1003]
If create a profile on the forum with the name "..." (three dots) and then mention this profile "@..." with other nicknames at the same post, the names in other mentions will automatically change to "@..." after post publication. But it must be said that all accounts still receive notifications about these mentions, despite the name change.

![issue with mentioning   name](https://user-images.githubusercontent.com/72157778/96109598-79491900-0ee7-11eb-840a-622c955b4338.gif)

**Comment by akinsey** [comment]
Thanks for the report ill take a look!
