### ISSUE TITLE
[Bug] issue with height attribute in the img tag

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1009]
Height attribute doesn't work in the image tag.

The GIF below shows the work of the image attributes on Bitcointalk and Coinbistro

![height attribute issue](https://user-images.githubusercontent.com/72157778/96284944-fad3a080-0fe6-11eb-8358-e49d39199f6e.gif)

Image link: https://static.currency.com/img/media/bitcoin.dd8a16.png

**Comment by ruesato** [comment]
Thanks, good catch! 

@Vele0r Can you send us a link to the bitcointalk post you showed in the gif?

**Comment by Rizzrack09** [comment]
@ruesato 
Coinbistro: https://coinbistro.com/threads/2381b396-0c80-405b-91ce-71143a27ae68/posts?start=100#CT5uadS9R0q7r4nv47PVRw
Bitcointalk: https://bitcointalk.org/index.php?topic=5221946.msg55393719#msg55393719
BBCode:
`[img width=100]https://static.currency.com/img/media/bitcoin.dd8a16.png[/img]`
`[img height=50]https://static.currency.com/img/media/bitcoin.dd8a16.png[/img]`

**Comment by Rizzrack09** [comment]
This is with the exact code frog the gif
Bitcointalk: https://bitcointalk.org/index.php?topic=5221946.msg55393942#msg55393942
Coinbistro: https://coinbistro.com/threads/2381b396-0c80-405b-91ce-71143a27ae68/posts?start=101#GTr8Q6XWT9y3U2_K7YiLTw
code:
`[table]
[tr]
[td]
WIDTH = 100
[img width=100]https://static.currency.com/img/media/bitcoin.dd8a16.png[/img]
[/td]
[td]
HEIGHT = 50
[img height=50]https://static.currency.com/img/media/bitcoin.dd8a16.png[/img]
[/td]
[/tr]
[/table]`
