### ISSUE TITLE
[Bug] issue with words containing capital letters after "@"

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1018]
Words that contain capital letters and follow the "@" character are enclosing in curly braces when posting.
This creates a problem for URLs. There is no such problem if in the word after "@" all letters are lowercase.
Also, if URL contains a word after "@", which is identical to a username on the forum, this link breaks.

See the GIF with this bug
![words and urls with symbol a](https://user-images.githubusercontent.com/72157778/96338990-4f842380-109a-11eb-9d18-f3c7ec1068a9.gif)

Code used for the test
```
1) @ICOCryptoNews
[url=https://medium.com/@ICOCryptoNews]@ICOCryptoNews[/url]
2) @Crypto
[url=https://medium.com/@Crypto]Crypto[/url]
```

Link to the testing post: https://coinbistro.com/threads/2381b396-0c80-405b-91ce-71143a27ae68/posts?start=102#mmmYYWCDSxuqLc_kAzIolQ

**Comment by akinsey** [comment]
Strange good find, I'll take a look!
