### ISSUE TITLE
[Bug] search finds a post without a keyword

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1026]
When I entered the word "Korner" into the [Search field](https://coinbistro.com/search/posts), the result showed me a post with an old edited comment without this keyword. I don't remember what exactly was in that post before editing, but maybe the word "Korner" was there at first.

![search finds a post without a keyword](https://user-images.githubusercontent.com/72157778/96362509-7bed7d80-1136-11eb-9cdf-bf74056c32f1.gif)

Link to found post: https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=19#YScVr46tQuiLKj-yzSyxHg

**Comment by akinsey** [comment]
That is most likely the case, this should be resolved for new posts. Can you try updating the post and see if its still found?

**Comment by Vele0r** [comment]
After I updated the post, the problem went away.
