### ISSUE TITLE
[Bug] can't upload images to the forum

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1039]
The last time I've managed to upload a picture to a comment was two days ago, apparently before the Coinbistro forum was updated to the version [27A00F2B](https://github.com/epochtalk/epochtalk/commits/27A00F2B).

**Comment by Rizzrack09** [comment]
@unenglishable @akinsey  When trying to add an image in a post or message the console shows error "maxImageSize is not defined" and is coming from the [err msg](https://github.com/epochtalk/epochtalk/blob/07734eab51afb92c51483628a5e8688d0f881c33/modules/ept-images/client/image-uploader.directive.js#L87), not the variable above
Also after removing maxImageSize from the err msg could not upload images bigger than 1MB even though forumData.max_image_size is set to 10485760 (tried adding another 0 and still did not work) and if purpose = avatar then it's 102400 as  14026ab . Can't figure out where it gets the 1MB restriction from.
On my local install I use local image file, not AWS... though I suppose it shouldn't make a difference.

**Comment by akinsey** [comment]
I will work with @unenglishable on this today, thank you!

**Comment by unenglishable** [comment]
should be fixed for general image uploads.  issues with small images (< 1kb) are still under investigation
