### ISSUE TITLE
[Bug] broken urls in watched threads list

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1040]
The ["Watched Threads"](https://coinbistro.com/watchlist/edit) list instead of topic links has the same broken URL:
`https://coinbistro.com/threads//posts`

The GIF below with this bug

![watched threads urls issue](https://user-images.githubusercontent.com/72157778/96767377-1f63ba00-13e5-11eb-950b-2cec6dd39999.gif)

**Comment by akinsey** [comment]
This is due to the slugs change, will fix, thank you!
