### ISSUE TITLE
[Bug] forum crashed after trying to upload a picture via "Avatar URL"

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1052]
When trying to upload an [animated GIF](https://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gif) 6,24 MB in size to my Coinbistro profile, via "Avatar URL" option, the forum crashed with the "502 Bad Gateway" error.

![coinbistro502](https://user-images.githubusercontent.com/72157778/97115450-dcb52100-1707-11eb-869b-98d5ddae0ca7.png)
http://coinbistro.com/

**Comment by unenglishable** [comment]
thanks, we're looking into it 👍 forum is back up for now

**Comment by akinsey** [comment]
Were not sure if this occurred before the avatar size restriction change. Can you try again and let us know if the issue still persists? I tried on Firefox and Chrome in Ubuntu and I'm getting a max image size exceeded error.

thanks!

**Comment by Vele0r** [comment]
After several attempts to change my avatar, the forum crashed again. Time event 12:33 am GMT
I used the Tor browser 10.0.2 (based on Mozilla Firefox 78.4.0esr) (32-bit)

My steps before this new crash:
1. At first, I was able to install a 6,24 MB [animated GIF](https://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gif) avatar via "Avatar URL" option in my profile without any problems.
2. I set my [old avatar](https://epochtalk-btc.s3-us-west-2.amazonaws.com/images/b2ca18bcef855901b14bf66e4acb9a6bfef44611.png) back and exited the browser.
3. I returned to the Tor browser and repeated the steps from reports #1049 and #1048.
    a) I used the "Prevent this page from creating additional dialogs" option in the forum topic "Epochtalk discussion'.
    b) I tried to add a website in Japanese (はじめよう.みんな) to my profile, but I was refused.
4. After that I was able to load the [animated GIF](https://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gif) again without any problems. But when I tried to get my [old avatar](https://epochtalk-btc.s3-us-west-2.amazonaws.com/images/b2ca18bcef855901b14bf66e4acb9a6bfef44611.png) back, the forum crashed.

**Comment by Rizzrack09** [comment]
@Vele0r would be awesome if you could replicate and also record

**Comment by Vele0r** [comment]
@Rizzrack09 I was able to reproduce this error. I will now download the video (about 4 minutes) and send you the link.

**Comment by Vele0r** [comment]
Link to the video: https://yadi.sk/i/cchHOC5qEUXqLw

At 01:50 of the video, I put a double link in "Avatar URL", without spaces:
https://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gifhttps://www.verdict.co.uk/wp-content/uploads/2017/09/giphy-downsized-large.gif

Just before the crash of the forum, I entered the "site.com" link in the "Avatar URL" field.

**Comment by unenglishable** [comment]
should not crash the forum anymore since #1061 
currently working on UI display for this error; it's due to inputting text into the avatar field which is not a link to a valid image
