### ISSUE TITLE
[Bug] issue with a blank report

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#1060]
If you open and close the "Report" window leaving it empty, then the next time you open it, the option to report a user's post will be not available. This can be fixed by reloading the page.

See the GIF

![blank report](https://user-images.githubusercontent.com/72157778/97316368-b6fc5900-187a-11eb-80f2-50b33ea000a2.gif)

**Comment by Rizzrack09** [comment]
It should be the same bug as mentioned in #988

**Comment by Vele0r** [comment]
The described bug should be fixed in the latest release [1.33.6.](https://github.com/epochtalk/epochtalk/releases/tag/v1.33.6)

Likely the Coinbistro forum has not yet been updated by this time.

In the near future I will return to the issues #988 and #1060, and if this bug doesn't appear, then I will close them.
