### ISSUE TITLE
S3 vars can't be loaded from a config file

### ISSUE THREAD

**Issue by taesup** [epochtalk/epochtalk#120]
It looks like putting any S3 configs in the configuration.json file will not be loaded. So the only way to set S3 vars is through the web ui after the server starts. Is this how it's going to be?

isthisrealife.jpg

**Comment by unenglishable** [comment]
yes, that's correct.  the s3 configs should be corrected/editable via admin panel (or whatever walkthrough we decide to add to the sass product)

**Comment by unenglishable** [comment]
this file should be renamed to something like "default-configurations.json" or something, because they are just that - defaults.

**Comment by unenglishable** [comment]
resolved by #157
