### ISSUE TITLE
TTY error on exiting npm run serve

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#124]
related commit: 2d24ead47f8efbd96773f0b0ae1f18d66e42eda7

it's a nodemon issue:  https://github.com/JacksonGariety/gulp-nodemon/issues/77

fix listed here: https://github.com/JacksonGariety/gulp-nodemon/issues/77#issuecomment-159450126

**Comment by taesup** [comment]
Fixed in 2bdc4419c1ed75dcc2fe51edc13c8bc4a732eac3
