### ISSUE TITLE
compressed URL

### ISSUE THREAD

**Issue by da2ce7** [epochtalk/epochtalk#162]
For the moment we have very long with full URI's.

eg: https://beta.bitcointalk.org/boards/AAAAAAAAAAAAAAAAAAAAAQ

Where it could be shortened to: https://beta.bitcointalk.org/boards/Q  Where the lease signifiant bits removed.

**Comment by wangbus** [comment]
We will have slugs in the future. but this is actually a result of compressing UUIDs from the UUID V4 spec.

**Comment by wangbus** [comment]
We're staying with compressed uuid's for now. closing til further notice but slugs will be implemented in a future iteration.
