### ISSUE TITLE
[Suggestion] Multiple topic/thread owners

### ISSUE THREAD

**Issue by hipio** [epochtalk/epochtalk#166]
I thought that it might be a good idea to have the option of multiple topic/thread owners. This would be very useful when managing a large thread with multiple people at once. A simple example would be a topic/thread containing information about a certain subject that is bound to change a lot, multiple owners could quickly respond to that change even if one of them is not around/busy or even left the forum.

**Comment by wangbus** [comment]
Great idea. Any suggestions on how the users be appointed as an owner?

**Comment by hipio** [comment]
In my opinion, the "_best approach_" would be a topic/thread with a primary owner and a list of co-owners. 

The owner would have the power to give over his role to one of the co-owners and as a fail-safe (in case someone leaves for example) it might be a good idea to have the option (as a co-owner) to press a button that would make them the primary owner within a certain amount of time (for example 7 days) if the current primary owner doesn't cancel it. That way a thread is always under the control of an active users (unless all of them go off-line/afk/etc).

You could even go so far that a random co-owner is picked when the current owner is banned (or some other way to solve it, maybe manual intervention by moderators).

**Comment by hipio** [comment]
[Example](https://gathering.tweakers.net/forum/list_messages/1744375) on a Dutch forum which clearly lists both Author and the co-authors. However, I do not know what they do when someone gets banned or becomes inactive.

**Comment by wangbus** [comment]
Need to digest this information. Will try to get back to you on this.

**Comment by akinsey** [comment]
Closing for now, will reopen if this becomes relevant again.
