### ISSUE TITLE
[Error] Editing Trust Settings returns 401 from the API

### ISSUE THREAD

**Issue by hipio** [epochtalk/epochtalk#170]
**How to reproduce?**

- Go to `My Profile`
- Click on `Edit Trust Settings`

You will be greeted by a `503 Service Unavailable`-message with the following error from the API:
``` Json
{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}
```

**Comment by wangbus** [comment]
Unable to reproduce locally. Can you confirm this happens on a new installation?

**Comment by hipio** [comment]
I will look into it. Might just that my Nginx proxy isn't passing all the data it should. 

Closing this ticket until I have more information.
