### ISSUE TITLE
messages for receiving user and for sender

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#203]
currently, the sender and receiver share an instance of a message.
if the sender sends a message and then deletes it, it gets deleted from the receiver's inbox too.

this leads to unreliability in places such as:  message history, accountability, and the list of notifications.

i suggest redesigning this feature to work more like email, with a copy of the message for each user, immutable by the other involved party 🎉 .  include documentation on the flow of messages.

**Comment by akinsey** [comment]
This is fixed
