### ISSUE TITLE
email sending isn't working, can't find anything in logs as to why

### ISSUE THREAD

**Issue by Yantrio** [epochtalk/epochtalk#211]
I'm having issues sending mail using my smtp server, I can't seem to find anything in the logs as to why. I can see the template being created, but nothing about an email actually being sent.

Where's the best place to start looking as to why this is failing? 

P.S, your gitter room is dead.
Cheers, Yantrio

**Comment by unenglishable** [comment]
Hey Yantrio, thanks for your interest in this project, and thanks for the note on the Gitter room!  - I'll bring it up to the rest of the team.  We're currently more active on Slack if you would like to join up there:  epochtalk.slack.com

The project currently supports Amazon Web Services (AWS) Simple Email Service (SES), but we might need to update the emailer to work with other services.  I can also include more logging to make it more apparent whether the emailer is working or not.

May I ask, which email service are you using?

**Comment by wangbus** [comment]
@Yantrio: Please pass over your email to one of us so we can send you a invite to the slack. Thanks for your interest in this project!

**Comment by Yantrio** [comment]
Hey guys, thanks for the reply, I'm currently looking at using just basic SMTP, but if that if that isn't supported, i'll look into pushing a pull request for it :) you can invite me to slack with the email `james at yantr.io` Thanks :)

**Comment by unenglishable** [comment]
Hey @Yantrio, just wanted to let you know, I'm working on updates to our emailer configurations.  With this revise, my intent is to allow full [nodemailer](https://nodemailer.com/about/) configuration of the emailer.

This may take a while to complete, and I'll come back to this issue when I'm done to see if you can get it working properly.  Until then, you can check up on the progress in issue #248.

**Comment by unenglishable** [comment]
resolved by #285
