### ISSUE TITLE
suggestion:  disallow modification of rate limits in the admin panel

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#214]
why is it bad?

* the admin can set rates which cause **our own app's API calls** to fail

* the admin can set rates which lock the admin out of updating the rates

   (EX:  setting the PUT request limit Interval to something high like 10,000,000 and the Max In Interval to something low, like 1 prevents all users from making more than one put request in over 2 hours, but also **prevents the admin from fixing that mistake** for the same amount of time)

* (etc)

i suggest that we set values on the server side.  instead of having _sane defaults_, we can just provide _sane values_ to begin with.

**Comment by akinsey** [comment]
As a compromise we should enforce sane min and max values so the server wont die
