### ISSUE TITLE
explicitly define API return values

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#223]
in some cases, we have this:

```
var promise = db.someshit(input);
return reply(promise);
```

that's "elegant" and all, but it is in no way **consistent**.  you have to go look at the db method implementation to tell what it returns.  more importantly, when the db method changes, the **return value of the API call changes**
it would be better like this:

```
var promise = db.someshit(input).then(result => {
  whatever: result.whatever,
  otherthing: result.otherthing
});

return reply(promise);
```

**Comment by akinsey** [comment]
this would've been nice
