### ISSUE TITLE
Delete board doesn't work as long as there is 1 thread or more in the board

### ISSUE THREAD

**Issue by wangbus** [epochtalk/epochtalk#252]
As long as there is at least 1 thread, it will kick back. We need to change this feature to a soft delete/purge functionality.

**Comment by akinsey** [comment]
Tested this in my branch it the delete feature seems to be working fine even when thread data in the board

**Comment by akinsey** [comment]
```
[error], message: update or delete on table "threads" violates foreign key constraint "posts_thread_id_fkey" on table "posts" stack: error: update or delete on table "threads" violates foreign key constraint "posts_thread_id_fkey" on table "posts"
```

**Comment by akinsey** [comment]
@wangbus are we missing a `on delete cascade` on the `posts` fk?

**Comment by akinsey** [comment]
@wangbus pls update

**Comment by akinsey** [comment]
@wangbus I think this is related to the dataset/migration as well.
