### ISSUE TITLE
modify emailer configuration database storage to allow flexible configuration

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#256]
related to #248 

we need to be able to choose whether to store or not store email configuration **fields**
in order to make use of different configurations, the _required fields_ must be flexible, and not cause database errors when optional fields are not included.

**Comment by unenglishable** [comment]
## tentative updates in emailer configuration (pending discussion)

My thoughts on and designs for emailer configuration.  Topics include:  Default configurations, Error Checking, ENV configuration, UI configuration.

### Default configurations

Remove the default configurations for the emailer.

It doesn't make any sense to set defaults, since the emailer will not work with the default settings anyway.

### Error checking

The current solution checks whether or not all of the values are set, throwing an error if there is a field which is not filled in.

To allow flexibility in emailer configuration, existing error checking will be replaced, and handled differently based on whether the emailer is being configured via ENV variable or UI.

Along with these changes,  email configuration verification will be done by sending a test email.

This can be done at server start, when configuring via ENV, and done on configuration update when configuring via UI.  Additionally, we can add functionality to send a test email at any time via a button (in the case that the email server is experiencing interruptions, and the emailer configuration has not changed).


### ENV configuration

When using ENV to configure the emailer, the emailer will be **entirely** configured through ENV.  These configurations should not be stored in the database, and should not read emailer configurations from the database at any point.

The configurations passed to `nodemailer` will be **exactly** as specified in ENV.  Fields will only exist in the js Object `options` field if they are specified in ENV.  To avoid configuration errors, nested fields will not be populated if they will only contain undefined properties.

```javascript
emailer: {
  sender: 'user@host.com',
  transporter: 'ses',
  options: {
    // passed directly to nodemailer(options)
    // or handled in transporters[transporter](options)
  }
}
```

Error handling:  Log configuration errors directly to the console.  These should come directly from `nodemailer`.

This will be the behaviour in SAAS mode as well since we are setting emailer via ENV.  This will also be the configuration style for developers who choose to use the environment variables.

### UI configuration

When using the UI to configure the emailer, ENV must not be set.  **All** emailer configurations will be stored to the database, including username and password.  Configurations should only be read through the database.

Tentatively, use radio buttons or dropdown menu to select the _type_ of email configuration.  Once selected, the user will be prompted with specific fields to fill in.  Any field that can be defaulted, such as host and port configuration for specific services,  should be set on server side.

Error handling:  

* Ensure that the user fills out all required (*) fields.
* Send a test email.
* For each configuration type, make sure we personally test it before adding to the list of UI configurable options.

**Comment by wangbus** [comment]
Look into:

* GPG encryption of server side configuration
* Console output of emails instead of email configuration (in development)

**Comment by unenglishable** [comment]
* consider drop-in emailer configuration file for server side configuration

* reconfigure database configurations to use `jsonb`

**Comment by unenglishable** [comment]
arguments against drop-in json emailer configuration file

https://blog.doismellburning.co.uk/twelve-factor-config-misunderstandings-and-advice/

**Comment by wangbus** [comment]
I think whatever direction we take this should have a 1-1 mapping with JSON vs ENV.

**Comment by unenglishable** [comment]
## In this refactor

* `jsonb` storage for database configurations

* console output of emails (as the default)

## Not in this refactor

* #257 **drop-in emailer configurations json file**
  i will implement the environment configuration for now, and add a github issue this as an enhancement

* #258 **gpg encryption for env**
  this will also be created as an enhancement issue.  it _is_ a security feature, but it is also not implemented yet, so there's no detriment if it's not included in the refactor

**Comment by unenglishable** [comment]
i would like to explicitly define and document the configuration logic flow.  if we can add tests on top of that (even just rudimentary ones) to ensure the logic is correct for each use case, that would be a double plus.

**Comment by unenglishable** [comment]
## Notes on documentation for configurations

* List of all configurations

* What can be set on startup, and not changed

* What can be changed after startup

* Immutability

* Defaults

**Comment by unenglishable** [comment]
added tasks #263, #264 

completion of this issue depends on those two.


finally, documentation is down as a requirement in #265
