### ISSUE TITLE
User search is broken in master with migrated data

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#272]
Searching users is broken because all migrated users have their `deleted` column set to `NULL` instead of false. To fix the issue we need to default the `deleted` column to `false` in the `users` table schema.

**Comment by akinsey** [comment]
Upon further investigation, creating a new user also has the deleted field default to NULL. By default when creating a new user the deleted field should be `false`. This should resolve the issues with search and possibly other features looking at the user.deleted field from not working.

**Comment by akinsey** [comment]
Any updates on this @wangbus?

**Comment by akinsey** [comment]
bump, this is still broken in beta.bitcointalk

**Comment by wangbus** [comment]
This one slipped through the cracks... I'm on it.

**Comment by akinsey** [comment]
This is related to the bitcointalk dataset @wangbus, we can make sure to test this once we get the dataset working.
