### ISSUE TITLE
Render posts on retrieval instead of on creation

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#277]
Rendering posts on retrieval instead of creation will allow us to get rid of the raw_body field.

**Comment by akinsey** [comment]
1. Remove the `pre` methods calling `common.*.parse` on posts, messages, threads and users routes

2. Modify the `parse` methods in common to append the parsed data to a new field called `body_parsed`

3. Updated client side html where `object.body` is being displayed and change to `object.body_parsed`

**Comment by akinsey** [comment]
**Design Notes**

**body** - The unprocessed body which contains Markup and BBCode
**body_html** - The processed body which contains HTML

1. Rename `body` to `body_html` and `raw_body` to `body` throughout codebase
2. Need to rename directives `body` and `raw_body` respectively to `body_html` and `body`
3. Need to fix mentions use of `raw_body` field, it might rely on this to create the mention
4. Change all DB code which is putting `content->body` into `raw_body` to put `content->body` into `body`

**Comment by akinsey** [comment]
Routes returning `raw_body` and `body`:

`ept-mentions/routes`
`ept-posts/byThread`
`ept-posts/create`
`ept-posts/find`
`ept-posts/pageByUser`
`ept-posts/update`
`ept-threads/db/getFirstPost`
`ept-threads/routes/create`
`ept-threads/routes/title`

**Comment by wangbus** [comment]
jesus christ that's a lot of areas.
