### ISSUE TITLE
admin panel emailer configuration templates

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#282]
the UI should have some sort of selector that lets the admin pick what kind of emailer configuration they would like to use, and shows the _relevant_ fields for running that configuration.

this way, we can handle different configurations, instead of writing a method that checks if all of the fields are filled out or not.

**Comment by akinsey** [comment]
If you go over the spec of this with me I can implement it

**Comment by akinsey** [comment]
bump
