### ISSUE TITLE
Invitations only can be sent once

### ISSUE THREAD

**Issue by wangbus** [epochtalk/epochtalk#296]
After the initial invitation, the GUI fails with this error. We should be able to send the invitation more than once. The only time that invitations cannot be sent is if the user is already in the system (or opts out in a future defined way).

<img width="356" alt="screen shot 2017-07-25 at 3 20 39 pm" src="https://user-images.githubusercontent.com/8233/28600362-37062668-714d-11e7-8a03-19b69295b3b5.png">

**Comment by akinsey** [comment]
I agree but i think there should be a limit, like once per 24 hours or so?

**Comment by akinsey** [comment]
After further investigation you can resend an email if you are an admin. Go to Admin->Management->Invitations
