### ISSUE TITLE
[Enhancement] Messages Change Notes

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#325]
I think it's worth revising the current messaging system as opposed to ripping it out and starting from scratch. I believe we can get what we want out of the current system if we implement a few changes.

**Changes to implement:**

# One
Possibly get rid of the ability to start more than one conversation with the same person. So if you're messaging the same user, it just creates a reply in the same conversation which is selected on the left. Currently you can have multiple conversations going with the same person. 

This might just be personal preference, as you may want to have multiple conversations about different things going with the same person. It just seems like it might be confusing with our current UI and users might hit the `+ New Message` button instead of replying in their existing conversation. So possibly this issue could be fixed with a UI revision.

# Two
Instead of deleting the message when one user deletes it, I believe we should set a flag on the message saying which user has it flagged as deleted. We can do this by creating a `deleted_by` column which holds an array of user_ids who have deleted the message. This prevents us from having to duplicate the message for each user. This should solve the issue of one user deleting a message, deleting the message of the other user.

To implement this we would need to modify the query to not bring back messages/conversations which have the user's id in the `deleted_by` column

# Three
Option to delete entire conversation, instead of deleting messages one by one

# Four
Implement CC and BCC  (optional)

Please review and let me know what you think @wangbus and @unenglishable

**Comment by wangbus** [comment]
If the `conversation` is deleted, all children `messages` are treated as deleted regardless of individual `deleted_by_user_ids` state.

**Comment by hipio** [comment]
I'm highly against `get rid of the ability to start more than one conversation with the same person`. 

I have over 150 pages of messages in my inbox and it would be a huge mess if all the messages, I had with one user, are merged together. Finding anything would be incredibly hard as well, since my PM subjects are descriptive about the content within.

**Comment by akinsey** [comment]
@hipio We've left the ability in and added a Subject field to distinguish conversations
