### ISSUE TITLE
seed roles in `node cli seed`

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#358]
from #355

**Comment by unenglishable** [comment]
roles are currently seeded on server startup.  remove this step from server startup and move the role seeding ability to `cli/index.js`

this update should modify `cli/index.js` to allow the script user to seed roles in the database.  any person or server starting epochtalk will have to call the seed script separately to seed the roles.

update the documentation to reflect this change.



as an added benefit, this will resolve timing issues with continuous integration testing and docker-compose schemes

**Comment by akinsey** [comment]
I think the seed can be left on startup, as it only updates if it sees changes if I recall correctly.

**Comment by akinsey** [comment]
I remember why it happens on startup. If we apply new permissions to existing roles in an update to epochtalk, the roles will be updated when the server restarts. If we only update the roles in the seed and only in the seed, we would have to find another way to push permission updates to existing roles.

My advice is to just not remove it from server startup, and add it to the seed as well, preferably in a dry and reusable manner. @unenglishable
