### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by latunoff** [epochtalk/epochtalk#373]
D:\als\angular\epochtalk-master>**npm install**
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try
 to do my best with it!
npm WARN deprecated node-uuid@1.4.3: Use uuid module instead

> bcrypt@0.8.7 install D:\als\angular\epochtalk-master\node_modules\bcrypt
> node-gyp rebuild

D:\als\angular\epochtalk-master\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Users\Latunov\AppData\Roaming\npm\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\Latunov\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\Latunov\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Latunov\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Latunov\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd D:\als\angular\epochtalk-master\node_modules\bcrypt
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@0.7.5 (node_modules\socketcluster-server\node_modules\uws):
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: No matching version found for uws@0.7.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch
":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Latunov\AppData\Roaming\npm-cache\_logs\2017-10-26T11_29_20_837Z-debug.log

D:\als\angular\epochtalk-master>

**Comment by akinsey** [comment]
Just a quick guess, but it looks like you need python to compile one of the dependencies.
