### ISSUE TITLE
[BUG] Startup log of configs isn't right

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#389]
The config that's printed when starting the server is too large, I believe properties are being duplicated, please look into this and fix @unenglishable

**Comment by unenglishable** [comment]
ok

**Comment by unenglishable** [comment]
looks alright to me.  pics or it didn't happen 📷

**Comment by unenglishable** [comment]
closing; there is no issue.  emailerenv and imagesenv are supposed to be there
