### ISSUE TITLE
don't try to send invites to users who are already registered

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#430]
when using the invite user interface, the current implementation checks that the email is a valid email, but *does not check* if the email is already registered.  when the invite fails to send for that reason, you're only left with a "Failed to invite user" message, although the interface says it should work before you send it.

![image](https://user-images.githubusercontent.com/3689811/35131665-8e992804-fc6b-11e7-8138-fc838a18ff7c.png)

**Comment by akinsey** [comment]
Sick ui
