### ISSUE TITLE
WEBSOCKET_HOST handles configuration for both epochtalk and websocket-server

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#437]
this is not logically the same variable for both servers.

the HOST for websocket-server is the host on which to bind.  (would be 0.0.0.0 in production)
the WEBSOCKET_HOST for epochtalk is the host where the websocket-server can be found.  (can be anything)

**Comment by unenglishable** [comment]
name suggestions:

WEBSOCKET_SERVER_HOST
WEBSOCKET_BIND_ADDRESS
WEBSOCKET_BIND_HOST
WEBSOCKET_QUANTUM_ENTANGLEMENT_HOST
EPOCHTALK_WEBSOCKET_HOST
WEBSOCKET_CONNECTION_HOST
WEBSOCKET_SERVER_MODULE_HOST

**Comment by akinsey** [comment]
WEBSOCKET_SERVER_HOST

**Comment by unenglishable** [comment]
@akinsey but within the websocket-server, why would it want to look at the WEBSOCKET_SERVER_HOST variable?  it already knows it's the websocket-server

**Comment by akinsey** [comment]
WEBSOCKET_BIND_ADDRESS

**Comment by unenglishable** [comment]
thanks @akinsey that's a really good choice, i think that's the right one
