### ISSUE TITLE
Update styles on Moderate view 

### ISSUE THREAD

**Issue by ruesato** [epochtalk/epochtalk#46]
Update the Moderate view with styles used in the admin views

**Comment by ruesato** [comment]
@akinsey can we add a class to <div ui-view=content> so we can assign it specific styles? Like we're doing with the Admin Moderate view <div ui-view=content class="admin-header">

**Comment by akinsey** [comment]
Should be good to go @ruesato the class is "public-content"

**Comment by ruesato** [comment]
forgot to tag in commit, but the styles have been updated here: https://github.com/epochtalk/epochtalk/tree/ui-admin-style

**Comment by CyrusV5** [comment]
So I guess this issue can be closed.
