### ISSUE TITLE
Posts Delete/Undelete causes posts to be orphaned

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#479]
Post order is not maintained and posts are deleted from the end of the thread and orphaned when following the steps below:

1) Create a thread 
2) Create 26 posts
3) Delete the 2nd and 4th posts
4) Undelete the 2nd post and the 4th and 5th posts will change place

**Comment by akinsey** [comment]
In smaller threads, this can cause the reply count to go negative.

**Comment by akinsey** [comment]
delete decrements reply count, but undelete does not reincrement reply count.

**Comment by akinsey** [comment]
The problem can be found when comparing ept-post modules db delete and undelete files. The delete file is running queries to decrement the users post count, update the thread updated_at, update the post positions and update the thread's post_count. The undelete file only toggles the deleted flag back to false.

**Comment by akinsey** [comment]
https://github.com/epochtalk/epochtalk/blob/master/modules/ept-posts/db/delete.js#L13-L19
https://github.com/epochtalk/epochtalk/blob/master/modules/ept-posts/db/undelete.js#L30

**Comment by wangbus** [comment]
Not enough 👀 on this. *sigh* Let's get this resolved soon.
