### ISSUE TITLE
Can't create default user.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#496]
Hello,

Currently the project work for me, but I have a problem, I don't have default admin.

When I try to run this command : `node cli --create`
I have this error : `error: unknown option '--create'`

Else, I have create a user with the website form, but how I can give admin role for this user ?

Thanks you.

**Comment by akinsey** [comment]
Apologies for the troubles, we will be updating the docs soon. You should be able to run the `node cli --help`

See this file:
https://github.com/epochtalk/epochtalk/blob/master/cli/index.js

@luluwebmaster

**Comment by luluwebmaster** [comment]
Oh, nice it's good, thank you !

**Comment by unenglishable** [comment]
@luluwebmaster Have you gotten the default user seed to work?  If so, I'll go ahead and mark this issue as resolved!

**Comment by luluwebmaster** [comment]
Hello,

Yes it's good, thank you ;)
