### ISSUE TITLE
Websocket problem

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#499]
Hello,

I have a little problem With Websocket, on my test forum : https://www.cryptos-currencies.com/

When I go to navigator console, I have this error : 

`WebSocket connection to 'wss://cryptos-currencies.com:23958/socketcluster/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

Here, my websocket configuration : 

```
## Set these if using websocket
## websocket client variables
DISABLE_WEBSOCKET_SERVER=false
WEBSOCKET_HOST=cryptos-currencies.com
WEBSOCKET_CLIENT_HOST=cryptos-currencies.com
WEBSOCKET_PORT=23958
WEBSOCKET_API_KEY={random-seed}
WEBSOCKET_SECURE=true
## websocket server variables
WEBSOCKET_SERVER_BIND_ADDRESS=cryptos-currencies.com
WEBSOCKET_SERVER_PORT=23958
WEBSOCKET_SERVER_PRIVATE_KEY={random-seed}
WEBSOCKET_SERVER_API_KEY={random-seed}
WEBSOCKET_SERVER_KEY_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/privkey.pem
WEBSOCKET_SERVER_CERT_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem
WEBSOCKET_SERVER_SECURE=true
WEBSOCKET_SERVER_REDIS_HOST=localhost
WEBSOCKET_SERVER_REDIS_PORT=6379
WEBSOCKET_SERVER_REDIS_OPTIONS_PASSWORD={random-seed}
WEBSOCKET_SERVER_REDIS_DB=10
```

Is it good ? Can you help me ?

Thank you !

**Comment by unenglishable** [comment]
Hey @luluwebmaster, your configuration looks pretty good so far.  I'll note here that `WEBSOCKET_SERVER_PRIVATE_KEY` should be set to the same value as `PRIVATE_KEY`.  In the same way the `WEBSOCKET_API_KEY` and `WEBSOCKET_SERVER_API_KEY` should be set to the same values as each other.

You probably also want to set `WEBSOCKET_SERVER_BIND_ADDRESS=0.0.0.0` instead of `cryptos-currencies.com`.  With your current settings, only networks devices on `cryptos-currencies.com` will be able to connect to the websocket server.
 
You could also try changing the `WEBSOCKET_SERVER_KEY_NAME` and `WEBSOCKET_SERVER_CERT_NAME` to ```WEBSOCKET_SERVER_KEY_NAME=/etc/letsencrypt/live/cryptos-currencies.com/privkey.pem
WEBSOCKET_SERVER_CERT_NAME=/etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem```

Because you're using an absolute path, there's nothing above the `/` directory.  Although default Linux behaviour redirects `/..` to `/`, I'm not sure if the nodejs code handles directories in the same way.

Finally, if you feel like it, you can set `WEBSOCKET_SERVER_ENGINE=uws` to enable a faster version of the websocket protocol.


Hope this helps!  Let me know if it's still not working and I'll take a look at it again 👍

**Comment by luluwebmaster** [comment]
Hello,

Thanks you for this help !

> Hey @luluwebmaster, your configuration looks pretty good so far. I'll note here that `WEBSOCKET_SERVER_PRIVATE_KEY` should be set to the same value as `PRIVATE_KEY`. In the same way the `WEBSOCKET_API_KEY` and `WEBSOCKET_SERVER_API_KEY` should be set to the same values as each other.

Thanks for that, I have change this.

> You probably also want to set `WEBSOCKET_SERVER_BIND_ADDRESS=0.0.0.0` instead of `cryptos-currencies.com`. With your current settings, only networks devices on `cryptos-currencies.com` will be able to connect to the websocket server.

I have change this, but not work.

> You could also try changing the `WEBSOCKET_SERVER_KEY_NAME` and `WEBSOCKET_SERVER_CERT_NAME` to `WEBSOCKET_SERVER_KEY_NAME=/etc/letsencrypt/live/cryptos-currencies.com/privkey.pem WEBSOCKET_SERVER_CERT_NAME=/etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem`

Hmm, I understand, but when I make that, I have this error in the console : 

![834f43fa](https://user-images.githubusercontent.com/15527061/53652964-6d451080-3c4a-11e9-90c9-e294fb129091.png)

> Because you're using an absolute path, there's nothing above the `/` directory. Although default Linux behaviour redirects `/..` to `/`, I'm not sure if the nodejs code handles directories in the same way.
> 
> Finally, if you feel like it, you can set `WEBSOCKET_SERVER_ENGINE=uws` to enable a faster version of the websocket protocol.

This module is not found ^^

> Hope this helps! Let me know if it's still not working and I'll take a look at it again 👍

**Comment by unenglishable** [comment]
Hey @luluwebmaster , please try pulling the branch `websocket-secure-fix` and running the app from there.  Be sure to install all packages.

In this branch, I updated the socketcluster package and re-did the configuration path for the websocket-server.

You should now be able to use a relative path from `epochtalk/` for your cert and key files.  I can update this again in the future to allow relative paths as well.

Anyhow, the main difference is in the environment variable `WEBSOCKET_SERVER_SECURE`.  That variable wasn't actually doing anything, and it should have been `WEBSOCKET_PROTOCOL` instead, set to `https`

```
 -WEBSOCKET_SERVER_SECURE=true
 +WEBSOCKET_PROTOCOL=https
```

Please try making this change in your `.env` file (in the `websocket-secure-fix` branch) and running again.  I believe the issue should be resolved.

Furthermore, the new name of the `uws` package is `sc-uws`.  However, I was not able to get it working with sc-uws:  I ran into an error with C++11 compiler not installed.  I hope they can resolve this issue some time in the future, but for now you can remove the environment variable `WEBSOCKET_SERVER_ENGINE`, which will default to regular `ws`.

Let me know how this goes!

**Comment by luluwebmaster** [comment]
Hello,

Sorry for the response time 🙄

I have trying your update, but does not work ^^

But, my config is it correct ?

```
## Set these if using websocket
## websocket client variables
DISABLE_WEBSOCKET_SERVER=false
WEBSOCKET_HOST=cryptos-currencies.com
WEBSOCKET_CLIENT_HOST=cryptos-currencies.com
WEBSOCKET_PORT=23958
WEBSOCKET_API_KEY={random-seed}
WEBSOCKET_SECURE=true
## websocket server variables
WEBSOCKET_SERVER_BIND_ADDRESS=0.0.0.0
WEBSOCKET_SERVER_PORT=23958
WEBSOCKET_SERVER_PRIVATE_KEY={random-seed}
WEBSOCKET_SERVER_API_KEY={random-seed}
WEBSOCKET_SERVER_KEY_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/privkey.pem
WEBSOCKET_SERVER_CERT_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem
# WEBSOCKET_SERVER_SECURE=true
# WEBSOCKET_SERVER_ENGINE=uws
WEBSOCKET_PROTOCOL=https
```

**Comment by unenglishable** [comment]
Please post the error you encountered - it will help me figure out what's wrong.

**Comment by luluwebmaster** [comment]
I have the same error : 

> When I go to navigator console, I have this error :
> 
> `WebSocket connection to 'wss://cryptos-currencies.com:23958/socketcluster/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

( I don't have error in server console )

**Comment by unenglishable** [comment]
Are you using some web server software like Nginx or Apache?  If that's the case, then you should be routing the websocket SSL traffic through there instead of using the built-in options.

Sorry, I actually should have asked about this first 😅 

If you're using Nginx, I can help you update your configuration.

**Comment by luluwebmaster** [comment]
Oh, yes I use Nginx for redirect trafic to Node Server ^^

**Comment by unenglishable** [comment]
Ah okay, you can use Nginx to route traffic to the websockets.  I think that's what is causing you to not be able to connect.


Change your environment file like this:
```
## Set these if using websocket
## websocket client variables
DISABLE_WEBSOCKET_SERVER=false
WEBSOCKET_HOST=cryptos-currencies.com
WEBSOCKET_CLIENT_HOST=cryptos-currencies.com
WEBSOCKET_PORT=23958
WEBSOCKET_API_KEY={random-seed}
WEBSOCKET_SECURE=true
## websocket server variables
  WEBSOCKET_SERVER_BIND_ADDRESS=localhost
  ## ^ change this to localhost!
WEBSOCKET_SERVER_PORT=23958
WEBSOCKET_SERVER_PRIVATE_KEY={random-seed}
WEBSOCKET_SERVER_API_KEY={random-seed}
  ## Remove WEBSOCKET_SERVER_KEY_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/privkey.pem
  ## Remove WEBSOCKET_SERVER_CERT_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem
# WEBSOCKET_SERVER_SECURE=true
# WEBSOCKET_SERVER_ENGINE=uws
  ## Remove WEBSOCKET_PROTOCOL=https
WEBSOCKET_SERVER_REDIS_HOST=localhost
WEBSOCKET_SERVER_REDIS_PORT=6379
WEBSOCKET_SERVER_REDIS_OPTIONS_PASSWORD={random-seed}
WEBSOCKET_SERVER_REDIS_DB=10
```

Mainly, remove or comment out the variables:  `WEBSOCKET_SERVER_KEY_NAME`, `WEBSOCKET_SERVER_CERT_NAME`, `WEBSOCKET_PROTOCOL` from the file.  Since you're routing through Nginx, you can change the server to bind address (`WEBSOCKET_SERVER_BIND_ADDRESS`) to` localhost` instead.  Later you'll configure Nginx to route traffic to the websocket server on `localhost`


Next, modify your Nginx configuration.

Add this configuration for `httpupgrade`
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
```
This will allow you to run `wss` traffic.

Next, add something like this to your server configuration to route traffic to the websocket server:
```
# create the upstream reference for websocket server
# point this to where you were running the websocket server
# localhost probably work because you set the server to bind to it
upstream websocket {
  server localhost:23958;
}

server {
  # (your https/443 server block)
  listen 443 ssl;

  ...

  location / {
    # (epochtalk server)
  }

  ...

  # socketcluster server / (websocket server)
  location /socketcluster {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # using previously created websocket upstream
    proxy_pass http://websocket;
  }

  ...

}
```

The `location /socketcluster` block is important here.  This is what will route the `wss` traffic to the websocket server.

If you do all of this, it should fix your issues!  Let me know if you are having difficulty and I can give you more info 👍

**Comment by luluwebmaster** [comment]
Hello,

Thank for this response !

After multiples tests, this does not work.

First, my Nginx Configuration ( nginx.conf ) : 

```
http {

        # .....

        map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
        }

        # .....

}
```

My Nginx website configuration : 

```
upstream websocket {
  server localhost:23958;
}

server {

        # Basic config
        server_name cryptos-currencies.com www.cryptos-currencies.com;

        # Root path
        location / {
                proxy_pass http://localhost:8080;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }

        # socketcluster server / (websocket server)
        location /socketcluster {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_http_version 1.1;
                # using previously created websocket upstream
                proxy_pass http://websocket;
        }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cryptos-currencies.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.cryptos-currencies.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = cryptos-currencies.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name cryptos-currencies.com www.cryptos-currencies.com;
    listen 80;
    return 404; # managed by Certbot




}
```

My .env config : 

```
## Set these if using websocket
## websocket client variables
DISABLE_WEBSOCKET_SERVER=false
WEBSOCKET_HOST=cryptos-currencies.com
WEBSOCKET_CLIENT_HOST=cryptos-currencies.com
WEBSOCKET_PORT=23958
WEBSOCKET_API_KEY={random-seed}
WEBSOCKET_SECURE=true
## websocket server variables
WEBSOCKET_SERVER_BIND_ADDRESS=localhost
WEBSOCKET_SERVER_PORT=23958
WEBSOCKET_SERVER_PRIVATE_KEY={random-seed}
WEBSOCKET_SERVER_API_KEY={random-seed}
# WEBSOCKET_SERVER_KEY_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/privkey.pem
# WEBSOCKET_SERVER_CERT_NAME=/../../../../../../etc/letsencrypt/live/cryptos-currencies.com/fullchain.pem
# WEBSOCKET_SERVER_SECURE=true
# WEBSOCKET_SERVER_ENGINE=uws
# WEBSOCKET_PROTOCOL=https
WEBSOCKET_SERVER_REDIS_HOST=localhost
WEBSOCKET_SERVER_REDIS_PORT=6379
WEBSOCKET_SERVER_REDIS_OPTIONS_PASSWORD={random-seed}
WEBSOCKET_SERVER_REDIS_DB=10
```

So, currently I have two problems : 

If I remove "WEBSOCKET_SERVER_KEY_NAME" and "WEBSOCKET_SERVER_CERT_NAME", the server can't start and return this error : 

`no such file or directory, open '/var/nodejs/cryptos-currencies.com/epochtalk/server.key'`

After that, I have trying to start with these variables, know, the server can start.

After that, I try to use Website, but in navigator console, I have a new error :

`WebSocket connection to 'wss://cryptos-currencies.com:23958/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Do I need to change the port in the configuration file ?

Note : Sorry for my bad English, I'm French ^^

**Comment by unenglishable** [comment]
Pull the latest version of the `websocket-secure-fix` branch.  I made some updates to the cert path defaults.  This should fix the `no such file or directory` error, and you can remove the variables again.

Also move the http upgrade map outside of any blocks.  It should be at the top level by itself.

Your website configuration looks good 👍 

It's possible that you could change `WEBSOCKET_HOST` to `localhost`.  The websocket server is running locally, and the EpochTalk app can connect to it on localhost as well.  The clients still need to connect to it via the internet though, so the `WEBSOCKET_CLIENT_HOST` value is correct!

**Comment by luluwebmaster** [comment]
Hello,

Thank you for the help,

But this does not work :-/

For the `map`, I can't move it at the top, if I make that, Nginx won't start.

I have change the `WEBSOCKET_HOST` to `localhost`, but I have the same error in browser console ..

Now, I don't know where is the problem :-/
