### ISSUE TITLE
Bugs or funcional issues on /www.cryptos-currencies.com test site

### ISSUE THREAD

**Issue by DdmrDdmrAlt2** [epochtalk/epochtalk#500]
This is derived from a test site someone has set-up to test Epochtalk, but probably everyone testing there will have a Bitcointalk perspective. Thay may lead to items being reported as bugs when they may really be functional deficiencies or even site configuration features. Theymos asked us to report them here, so here is what I found so far (see https://www.cryptos-currencies.com/threads/fd5dMTGLSJilQPxsZtmhmg/posts for the full thread that people are creating and the test site itself). Note that this is only my batch of items, as there are others who will likely report soon here too.

Some of the apparent bugs we may find could have to do with system configuration, as perhaps there are parameters that can be set by the Admin to customize the environment such as lack of edit tool bar, post max. size, etc.  At this point, bugs and lack of functionality (compared to current Bitcointalk) may be confused. I'll try to skip reporting things that have already been mentioned.

These are a few I’ve found so far:

1) Copy/paste post from Bitcointalk seems to confront size limitations-> post is trimmed to around 600 words out of 1285 of the OP.

2) Screen width is not taken into account as much as on the Bitcointalk site: posts here are cropped by around 25% on my screen (wide 4k). Also zooming in to screen on Bitcointalk redistributes post text accordingly, while here it does not do it if you shrink the screen size (it does if you enlarge the screen a lot).

3) Some text with spaces that displays aligned on Bitcointalk does not here. Possibly due to the default text font being different (when I copy text into word from this site it displays as “lato”, whilst being “calibri” when doing the same from Bitcointalk).

4) When I try to snip  in a quote the way I normally do it  (less than + 2 dots+ greater than), the preview and post actions delete the snip.  That is weird, and when importing all Bitcointalk could be an issue.

5) I can edit my profile UserName. That seems to be the PK to each user.  If I can change it, that could be troublesome (let alone for scraping and joining data, but that is a lesser issue from the forum's perspective).

6) Although already mentioned, not being able to delete a post, but only hide it is weird.

7) (minor issue) “Code” embraced areas seem to add a few blank lines on its own will, making the code area larger than necessary.

8 ) (minor issue) Direct urls  are sometimes converted to hyperlinks and others not (dictionary based?).

9) “Too many request” appear twice on screen. We are not many concurrent users, so it’s strange to see it.

10) Imported someone’s small pyramid quote. Displays fine but dates are wrong and relative to 1970.

11) Created 15 posts. I deleted one of them, and @iasenko another on a self-moderated thread. Nevertheless, my activity shows as 14 (not 13 as I expected). Also there is no post count. Post deletion seems to hide posts, but perhaps it is not adjusting Activity properly.

12) While on my profile, my post history has a very small thread title space (so it tends to appear trimmed).

13) There is no post number in the personal post history. If there are campaigns, counting posts will be a bit more difficult in relation to how it is done on Bitcointalk.

14) In addition, post history is only relative to thread, but we do not see the path to the thread as we currently do on bitcointalk (section/subsection/etc.).

15) I can see a post of mine on two pages of the paging of a given thread. If I change the setting to allow 50 post per page (instead of 25), then the post only shows once as it should. The post is last on the first page of the thread (post number 25 - if there were a number), and second on the following page (post number 27 - if there were a number).

16) Management of deleted posts seems a bit of a mess. A post of mine was deleted on a self-moderated thread. Nevertheless, I was still able to unhide it, edit it and quote it.

17) In the Notification menu, marking one or all as read does not refresh their status until you actually refresh the page itself.

18) This seems odd. I received 3 PMs from one single user (ok), but the Reply I create does no reference, nor let me decide, which of the three PMs I'm replying to.

-- Edit 20190317
19) (functionality) I can Deactivate/Reactivate my account, and that hide my account and all my posts from the forum: Good for the user, bad for the forum ?

20) After browing notifications, you need to refresh the page for the new notification counter to disappear.

**Comment by akinsey** [comment]
Can you please clarify on the following issues:

#4, I don't follow sorry, could you explain a bit more?

#11, What do you mean there is no post count? Also by delete do you mean hide or purge? We currently aren't accounting for deleted posts in activity as it should be inconsequential as your activity is capped at a certain amount per 2 weeks. I'll discuss fixing this with the team, but not high priority for now

#12, Can you get me a screen cap of what you're seeing? Thanks!

#14, is this in regards to the thread view or an individual users post history

#17 and #20, this sounds like a misconfiguration of the websocket server (I will still take a look at this though)

These were intentional, but I'll re-evaluating these with the team:

#6, I will discuss the usefulness of hiding vs deleting with the team

#13, I see what you are talking about, will discuss

#18, We are aware of the issues with the PM system, will revaluate this feature with the team

#19, We can discuss disabling this feature for BCT (Having an option in the settings)

Any of the other issues not mentioned above already had, or I've created a new issue for. Thank you for the help debugging the forums!

**Comment by DdmrDdmrAlt2** [comment]
Hi, 
Some clarifications as per your request:
#4,  Often when I quote a post, I just keep a snip as the post’s body such as this: <...>
The <...> is effectively removed when I type it in a message on Epochtalk, so I cannot use what I currently use on Bitcointalk. That may or may not be an issue upon migration, but would likely be one post-migration if viewing or editing posts with that for of snippet.


#11, On Bitcointalk, You can (configure) to see a user’s post count on a thread, just by the activity counter and under the Avatar. It could be a parametrization feature, but I was not able to see it.
The Deletion (Hide and so on) is a bit confusing, since, coming from Bitcointalk, hiding is not a feature, but rather deleting (at least at UI level). Unhiding seems weird and problem prone (hide things and show them again later down the road), but it may be a requirement that we are not aware of and the benefits of the solution unknown to us.
What happened if I recall correctly is that I deleted (hid) a post of mine, and another user deleted a post of mine from a self-moderated thread. My post count should have decreased by 2, but it only did by one.

#12, https://i.imgur.com/WM5HtCq.png. Note that thread column is very narrow, and does not show even when expanding on the separator between thread title and post.


#14, It’s regarding to individual profile Post view. On the thread view it is visible on the top of the screen as expected, but on the individual Post view we lose track of the related thread branch structure to the post (which is present on Bitcointalk).

#17 and #20 Ok. From a user point of view, it is confusing, but as you say it could be instance related.

#6, Ok ,thanks.
#13, Ok, thanks.
#18, , Ok, thanks.

#19, Ok, thanks

As a general comment, most if not all the testers on “Cryptos Currencies” site come from Bitcointalk, and therefore have that as a reference. That kind of leads us to envision a superset of the current Bitcointalk, and that is the comparison framework for most. Functional variations will therefore be harder to  grasp with no on-site description of them, and may therefore be reported as bugs whilst being otherwise.

Regards,
  DdmrDdmrAlt2

**Comment by akinsey** [comment]
#4, I just removed stripping of html tags from the post body. Angular sanitizes the html before it's displayed so it was unnecessary. This should fix that issue I think. Everything that looked like an html tag was removed prior to the fix.

The fixes are in my branch `fixes-2019`

**Comment by akinsey** [comment]
#11, I'll discuss how hiding/deleting should work with the team. Currently hiding does not decrease your post count, only if a moderator were to actually delete your post would your post count decrease.

#12, Thank you for the screenshot! I've made a new issue for this #516

#14, Got it! We will tackle this in #516

#17 amd #20, I'll talk to @wangbus about getting in touch and making sure the websockets are configured properly, or if it's due to a bug.

This shouldn't be a problem! Features that are specific to crypto forums can be written in a module which will allow them to easily be removed from sites with no need for those features. We just have to figure out what features those might be, for example the "bct-trust" module is optional.

Thank you for your help/input it's greatly appreciated!

**Comment by DdmrDdmrAlt2** [comment]
> #4, I just removed stripping of html tags from the post body. Angular sanitizes the html before it's displayed so it was unnecessary. This should fix that issue I think. Everything that looked like an html tag was removed prior to the fix.
> 
> The fixes are in my branch `fixes-2019`
Ok thanks. I guess that the site admin need to update the software for the fix to take place on hist test site.

**Comment by DdmrDdmrAlt2** [comment]
<...>
> This shouldn't be a problem! Features that are specific to crypto forums can be written in a module which will allow them to easily be removed from sites with no need for those features. We just have to figure out what features those might be, for example the "bct-trust" module is optional.
<...>
Ok .. Wondering if their is a Merit Module, or how that would be tackled. 
Regards
  DdmrDdmrAlt2
