### ISSUE TITLE
[BUG] Test forum : Arabic text.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#501]
Hello,

Texts in Arabic characters mixed with Latin characters are not placed to the right of the page.

When typing this : 

![image](https://user-images.githubusercontent.com/15527061/54481477-84345700-4835-11e9-8c34-290f02ec2b28.png)

The result is : 

![image](https://user-images.githubusercontent.com/15527061/54481481-8d252880-4835-11e9-94c2-c804fcac79ce.png)

Original bug post : https://www.cryptos-currencies.com/threads/pGaDkDv7TfWJf4gY3_SV0Q/posts

**Comment by akinsey** [comment]
Added Text Direction support for boards in the `fixes-2019` branch. It also requires that you pull the latest migrations from the `epoch` project and run `mix ecto.migrate`.

![https://i.imgur.com/ZM4hRHd.png](https://i.imgur.com/ZM4hRHd.png)
![https://i.imgur.com/JLGKMhX.png](https://i.imgur.com/JLGKMhX.png)

**Comment by akinsey** [comment]
@boka will need your help resolving issue with boards in api tests https://circleci.com/gh/epochtalk/epochtalk/1786?utm_campaign=build-failed&utm_medium=email&utm_source=notification

I added a new field to the boards: `right_to_left`
