### ISSUE TITLE
Back to the lines not correctly show.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#529]
Hello,

In the last version, the back to lines are not correctly show : 

Original : 

![image](https://user-images.githubusercontent.com/15527061/56448332-61063700-630e-11e9-80f9-2794260b3d31.png)

Final view : 

![image](https://user-images.githubusercontent.com/15527061/56448302-3c11c400-630e-11e9-87b7-4fc87bb402c1.png)

**Comment by akinsey** [comment]
I will look into this!

**Comment by akinsey** [comment]
Try pulling and let me know if the issue is resolved @luluwebmaster 🙏
