### ISSUE TITLE
Remove the name of the moderators shown in a board if there is none

### ISSUE THREAD

**Issue by zmitzie** [epochtalk/epochtalk#53]
![epochtalk forum](https://cloud.githubusercontent.com/assets/5725736/6404648/dee18b9c-be22-11e4-853c-28ce145808a0.png)

As you can see, there are no board moderators assigned in this board. However, the forum shows 3 Unknown messages next. This could be problematic, if some boards have no board moderators assigned. If that's the case, this line should not appear at all

**Comment by CyrusV5** [comment]
It's just dummy text until that functionality is implemented. But it could be removed just as well.

**Comment by taesup** [comment]
Fixed in 2948ad5b085658713e50e9ec1c338d1f10198208
