### ISSUE TITLE
Url detection problem

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#546]
Hello,

In the test forum, this url is not detected :

![image](https://user-images.githubusercontent.com/15527061/57227759-7bc8f300-7012-11e9-8bc8-3263830d4cea.png)

Original post : https://www.cryptos-currencies.com/threads/N7bCRMBcR92pmkJqmYmnVw/posts

**Comment by akinsey** [comment]
Will look into this thanks!

**Comment by akinsey** [comment]
Will look into this thanks!
