### ISSUE TITLE
field validation and format for date of birth is unclear (safari browser)

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#553]
as far as i can tell, it is impossible to set a date of birth

** edit:  this happens in Safari, date module works correctly in chrome

**Comment by CyrusV5** [comment]
AFAICT it's working on FF. Though whatever input you select (dd/mm/yyyy) the date selector is the same - not 100% intuitive but it's ok.

**Comment by unenglishable** [comment]
thanks, @CyrusV5 

here's a screen cap of what it looks like on safari
![image](https://user-images.githubusercontent.com/3689811/57962636-0af8c500-78b5-11e9-9dd2-3c5f619417f6.png)

**Comment by CyrusV5** [comment]
Here's a screen cap from FF:
![Annotation 2019-05-24 191350](https://user-images.githubusercontent.com/4005189/58341956-25ecab80-7e58-11e9-9f8f-b4d69273e658.png)
