### ISSUE TITLE
[BUG] Test forum : "Quote bar" not correctly placed in arabic section.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#568]
Hello,

The "quote bar" is not correctly placed : 

![image](https://user-images.githubusercontent.com/15527061/59557180-d8390e00-8fd3-11e9-88d9-dd0ab6c1e452.png)

Original bug post : https://bitcointalk.org/index.php?topic=5115500.msg51466968#msg51466968

**Comment by akinsey** [comment]
I will look into this!
