### ISSUE TITLE
[BUG] Test forum : Private messages not correctly formatted.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#570]
Hello,

The privates messages are not correctly formatted : 

![image](https://user-images.githubusercontent.com/15527061/59557247-2864a000-8fd5-11e9-8b82-623edf049628.png)

The formatted message : 

![image](https://user-images.githubusercontent.com/15527061/59557261-68c41e00-8fd5-11e9-9b8f-328500e84375.png)

And for the preview, it's the opposite, the back space are duplicated : 

![image](https://user-images.githubusercontent.com/15527061/59557270-a9239c00-8fd5-11e9-9338-2f8dc3e8e46f.png)

**Comment by akinsey** [comment]
Will be fixed soon, thank you for reporting

**Comment by luluwebmaster** [comment]
Hello,

Okay thank you !

**Comment by akinsey** [comment]
This should be resolved in the latest `master` branch code! Let me know if you have any issues

**Comment by akinsey** [comment]
This should actually be fixed now in master, sorry!

**Comment by luluwebmaster** [comment]
Thank you !
