### ISSUE TITLE
[BUG] Test forum : Privates messages not correctly sorted.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#571]
Hello,

I don't know why, randomly the private messages are not correctly sorted.

Ex : 

![image](https://user-images.githubusercontent.com/15527061/59705187-2d586800-91fe-11e9-8cb6-e96471148998.png)

**Comment by akinsey** [comment]
Thank you for reporting this! The messaging system is going to be written very soon! It is high on our priority list and will be reimplemented in a more user friendly manner

**Comment by unenglishable** [comment]
@luluwebmaster Can you give us some information on how to reproduce this?  We just need a list of the steps you did that made it go out of order.

**Comment by luluwebmaster** [comment]
Hello,

In this exemple : 

![image](https://user-images.githubusercontent.com/15527061/60595881-24dc6180-9da8-11e9-871f-612e61037949.png)

Steps by steps : 

- Send first message to "lulucrypto" -> Ok
- Send response with "lulucrypto" -> Ok ( Added in top messages list )
- Send response with "Luluwebmaster" -> Ok ( Added in top messages list )

But I see the problem when I reload page ( Check the Screen ).

**Comment by akinsey** [comment]
This should be fixed now!

You will need to pull the `epoch` project and run `mix ecto.migrate`

Then you need to pull the `epochtalk` project as well. You can now switch back to `master` branch if you aren't on it currently.

**Comment by luluwebmaster** [comment]
It's good, thank you !
