### ISSUE TITLE
[BUG] Test forum : Images does not work.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#572]
Hello,

When images are added in a post, they do not appear to be displayed

![image](https://user-images.githubusercontent.com/15527061/59705600-00588500-91ff-11e9-9e39-40b51aafe866.png)

**Comment by akinsey** [comment]
This was a bug caused my me trying to fix the parser. It has been fixed in our latest code which will be merged into master very soon. Thank you!

**Comment by akinsey** [comment]
Hello @luluwebmaster we’ve recently pushed a major code refactor and we will have to walk you through a couple of steps to get your current installation up to date. Some of the issues you've opened may have been fixed including this one, once we have your guys installation up and running we can start working on fixing specific bugs you guys have.

1) Pull the latest master for epochtalk

2) Run `yarn` in the root of the epochtalk project

3) Checkout the latest code for the epoch project:
https://github.com/epochtalk/epoch
Change directories into this project and run
```mix deps.get
mix ecto.migrate```

4) Clear your old roles from the database (you will have to recreate your roles if you’ve customized them, sorry) we’ve changed the way permissions are being loaded for a lot of the routes. To do this connect to your Postgres DB using `psql`

```SET session_replication_role = 'replica';
DELETE from roles;
SET session_replication_role = 'origin';```

This will allow you to delete the roles without removing all the users from those associated roles. The roles will be reinserted on restart of the epochtalk server and any users within those roles should still be there.

5) That’s it, everything should be up to date. If you have any issues just let us know.

**Comment by luluwebmaster** [comment]
Hello,

Right it's now good !

Thank you 👍

**Comment by akinsey** [comment]
Thank you!
