### ISSUE TITLE
[Suggestion] Test forum : Add guest role in role list.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#575]
Hello,

I have a suggestion based on my use.

I have tried to manage Guest permissions, but it's not possible ( Or I do not know where it is ).

My final goal is to be able to give permission to the guests to see the announcement messages.

Thank you !

**Comment by akinsey** [comment]
This was a bug, thank you for reporting! The anonymous role should have had permissions to see the message content.
