### ISSUE TITLE
[BUG] Test forum : New problem with URL's detection.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#584]
Hello,

For information, there is still a similar problem : 

![image](https://user-images.githubusercontent.com/15527061/60598144-7981db80-9dac-11e9-863c-9806826d82d0.png)

_Originally posted by @luluwebmaster in https://github.com/epochtalk/epochtalk/issues/502#issuecomment-508108116_

**Comment by akinsey** [comment]
Thank you I will look into this shortly
