### ISSUE TITLE
[bug] Long board description breaks words at end of line

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#585]
On the main page board description breaks words
![YzSvwoO](https://user-images.githubusercontent.com/51131936/60810892-bb3cc880-a196-11e9-9bfe-ef5f66314e2b.jpg)

bug post: https://coinbistro.com/threads/-_QYNP3LS12pF1wsNvzv-Q/posts

**Comment by akinsey** [comment]
Thank you for the report!

@ruesato looks like an issue with word-wrap css
