### ISSUE TITLE
[bug] HR overlaps ignore button

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#586]
On boards where trust is enabled hr line overlaps ignore button
![hr](https://user-images.githubusercontent.com/51131936/60811963-1374ca00-a199-11e9-91f0-25511e6688ad.jpg)

bug post: https://coinbistro.com/threads/XtDQbBvSQZWD7gZYyiFZoA/posts

**Comment by akinsey** [comment]
Noted! Thank you!

@ruesato
