### ISSUE TITLE
[proposal] email notification link

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#587]
E-mail notifications for quotes/mentions display link to op in thread. Should have the post`s permalink
Link in e-mail: https://coinbistro.com/threads/I4GzlgyAQFuRznEUOieuaA/posts
![email_link](https://user-images.githubusercontent.com/51131936/60815739-ef1ceb80-a1a0-11e9-8d47-c4f40fb6df25.jpg)
Post's link is: https://coinbistro.com/threads/I4GzlgyAQFuRznEUOieuaA/posts?start=35#hjkWj8bNQoK4I7lBQ7_Fbw
![post_link](https://user-images.githubusercontent.com/51131936/60815772-0360e880-a1a1-11e9-8c05-3bf7818d88a3.jpg)

bug post: https://coinbistro.com/threads/lcoSHt4ARJW1hMWtvH7KwA/posts

**Comment by akinsey** [comment]
Will look into this soon! Thank you

**Comment by akinsey** [comment]
Hello! thanks for the report!

We actually dont have email notification implemented for mentions yet! When you create a new thread you are automatically subscribed to email notifications for that thread. This means whenever you get a reply to the thread, it will email you. You can disable this in the Dropdown by your username then -> settings. Toggle off thread notifications.

This link should still link you to the last page of the thread so thank you for the report!

**Comment by unenglishable** [comment]
Seems to be resolved.  Please reopen if this becomes an issue
