### ISSUE TITLE
start server 

### ISSUE THREAD

**Issue by Abd3lk4d3r** [epochtalk/epochtalk#60]
Hello it seem that i can't start the sever after installing epochtalk ,
Maybe package.json doesn't contain start is this the problem ??
Please help me fix this .

Kind Of Respect .

**Comment by taesup** [comment]
So the readme is a little outdated, please use 'npm run serve' to start the server. 

Before you do this, make sure you have all the dependencies installed and running (Postgres). Also make sure that you've run the 'npm run db-create' and 'npm run db-migrate' commands before you run the serve command. 

This may change in the future as the project is still under heavy development.

**Comment by taesup** [comment]
README has been updated with latest startup commands. 

Also, please make sure that you have an a database.json file in the project directory with accurate information in it. There's an example database.json file provided for you in the git project.

Will be closing this issue for now.

**Comment by Abd3lk4d3r** [comment]
How is the structur of the database.json ?? I'm installing mysql on my apache will it work 
And Thank you very much for help .

**Comment by taesup** [comment]
There's an example database.json file provided in the git project. Please reference that.

Also, mysql will not work.
