### ISSUE TITLE
spacing when quoting V0.2

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#603]
> If you start writing the message on the next line below end-quote it adds additional next-line
> I would assume most users would write on the next line, to have the text looking smoother
> FIrst next line shoul not be taken into account by the editor
> ...
> 

Issue #598 

When multi-quoting spacing is broken also before quote. Would be better to have an additional next line before quote, and one less after quote
![Capture](https://user-images.githubusercontent.com/51131936/61221100-6b26ae80-a720-11e9-9a48-7bddc50c17fc.JPG)

bug post: https://coinbistro.com/threads/omW6GtkuQPqqsFUaZDjDTw/posts?start=4#WKYPot3gRiCQuEAnUEWavg

**Comment by akinsey** [comment]
Which one of these is correct? 

A:
![Screen Shot 2019-07-15 at 11 32 34 AM](https://user-images.githubusercontent.com/1738682/61250815-6815c900-a6f4-11e9-9e2c-cf0363d2e22d.png)

B:
![Screen Shot 2019-07-15 at 11 33 09 AM](https://user-images.githubusercontent.com/1738682/61250816-6815c900-a6f4-11e9-9ad1-9edb056f18c5.png)

A or B?

**Comment by CyrusV5** [comment]
I'd personally prefer B (and it's how I format my quotes as well). Makes it easier to see what reply goes to what quote IMO.

**Comment by CyrusV5** [comment]
I'd personally prefer B (and it's how I format my quotes as well). Makes it easier to see what reply goes to what quote IMO.

**Comment by Rizzrack09** [comment]
This is the default quoting format on bitcointalk:
![quotingbtct](https://user-images.githubusercontent.com/51131936/61288017-ee064280-a7ce-11e9-8113-a326a17abd1b.JPG)
And each user formats it how they feel fit (option A, option B , C, D....etc.)
Tho I agree with Cyrus that option B would be the way to go :)

**Comment by akinsey** [comment]
Thank you! I've modified it and taken out the margins like you show there, the user can now format it however they see fit like you said 🙌
