### ISSUE TITLE
[bug] Last post issue

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#612]
The last post option does not display posts in sub-sections
See below that the last post is displayed as being from Coin_BoT on 8 July
![board](https://user-images.githubusercontent.com/51131936/61702572-b8220a80-ad48-11e9-9869-72a42aec0d4b.JPG)
Even tho I posted in a Marketplace sub-sub-board much more recently, on 23 July:
![subsection](https://user-images.githubusercontent.com/51131936/61703898-413a4100-ad4b-11e9-898a-dc6c2d209415.JPG)

Seems the current behavior is to show last post in the exact board. If you are on the sub-board you are displayed the lost post only there as well. Might need a slight teak   

Bug post: https://coinbistro.com/threads/c5FN_n17TLeYN1i_Mr84wQ/posts

**Comment by akinsey** [comment]
I believe I know what the issue is here, I will look into it soon!
