### ISSUE TITLE
[proposal] threads started and differenciating OP from post

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#638]
Would need to make a clear differentiation between normal post in an existing thread and thread starting post  
Another button on the user profile would help .
Right now you are displayed "Posts by X" . Would help to also have "Topics started by X"
Also in the user post history there is no clear difference between OP (thread starting posts) and regular replies.

Post: https://coinbistro.com/threads/mNHIT5S0RsK3yrTvIclypA/posts

**Comment by unenglishable** [comment]
This will be broken into two features "Threads started by", and "Show OP in thread"

**Comment by unenglishable** [comment]
See #653 and #654
