### ISSUE TITLE
Handle recreation of client for s3 when settings change

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#64]
Currently updating s3 settings while the app is running is not supported by the image server, we need to add code to handle removing/recreating the client. See s3.js for reference.

**Comment by akinsey** [comment]
Test to see if this is still an issue

**Comment by wangbus** [comment]
Is this still an issue? cc: @akinsey, @unenglishable

**Comment by akinsey** [comment]
Doesn't appear to be an issue see https://github.com/epochtalk/epochtalk/blob/master/server/routes/admin/settings/config.js#L294
