### ISSUE TITLE
[proposal] ignore boards option

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#640]
On bitcointalk.org users have the option to ignore certain boards from the  profile settings. Feature often used by many members. It is displayed as a list of all the boards with check boxes to select which one to ignore. 
"Ignore boards" just means you don't see that board anymore, it's hidden, but you still can view threads if you have the direct URL
Many users on bitcointalk.org use this option and as I saw it's pretty important for them...

Post: https://coinbistro.com/threads/zWkz8-C1S76j81N36Bt9QA/posts

**Comment by akinsey** [comment]
Merged into master
