### ISSUE TITLE
[bug] mentions in edited posts

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#646]
If post is edited to add mentions they do not work/display correctly 
Only work if they are added from the beginning

Post: https://coinbistro.com/threads/cejaxrM6SC2OlbEyCCKs0w/posts

**Comment by unenglishable** [comment]
This is an intended behaviour.  In reduce spamming, we prevent notifications from happening on edit.  Otherwise, all mentioned users will receive a notification any time the post is edited.

This is consistent with most services that use notifications.
