### ISSUE TITLE
[bug] board view without proper permission

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#647]
If normal users access the direct link for a post that is in a board that requires certain permissions (Moderator + ... for example) they should be displayed an error message of sorts. Right now it just displays an empty page.

Post: https://coinbistro.com/threads/Vnf9wMAqSfCDpH2HnMXj0g/posts

**Comment by akinsey** [comment]
This is a bug, caused by an upgrade to angular ui router. Before this, users who didnt have permissions to view a board would just receive a 404 when visiting a board without proper permissions. I will look into this!
