### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by nahtnam** [epochtalk/epochtalk#67]
Hey!

It would be great if, in the end you guys packaged it to docker so that it can be easily deployed by anyone.

Thanks.

**Comment by taesup** [comment]
There are plans to dockerize the project at some point but it may be further down the road from now.

**Comment by nahtnam** [comment]
Kk. Thanks!

**Comment by wangbus** [comment]
Starting to work on this now.

**Comment by nahtnam** [comment]
:heavy_plus_sign:

**Comment by wangbus** [comment]
:blush:

**Comment by taesup** [comment]
@unenglishable Can we close this now? You got this to work right?

**Comment by unenglishable** [comment]
yeah, it works n' stuff.

**Comment by CyrusV5** [comment]
Awesomesauce
