### ISSUE TITLE
global moderator can't unlock a post locked by board moderator

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#686]
to reproduce, make a post and lock it as a board moderator; try to unlock using a global moderator account

**Comment by akinsey** [comment]
I cant seem to reproduce this, any more info? Have you reloaded both your global and regular mod roles. 

Also what role was the user who's post you were modifying

**Comment by unenglishable** [comment]
@akinsey seems to be working now.  fix-auth branch probably had the fix in it 👍
