### ISSUE TITLE
[clarification] Patrol page

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#709]
Right now I noticed that the user needs to be added in the patroller user role list from the admin panel in order to access the patrol page. They should be able to do this themselves from the profile page.
On the patrol page you are displayed a list of the last 200 posts made by newbies, regardless of board/thread .. just sorted by creation date.
More details here: https://coinbistro.com/threads/H2VUGYPaRMincvTbO5Oshw/posts

**Comment by akinsey** [comment]
The patroller role allows the user to moderate newbie posts from the patrol page. That looks like a new page that we will have to implement!

**Comment by Rizzrack09** [comment]
They are 2 separate things unfortunately named the same
- patroller as a ROLE should mean that these users have some basic moderation privileges only over newbie accounts witch mostly means delete newbie posts. It isn't more special than any other role. Just a random role with some permissions. That's all folks.
- the Patrol Page is just a page that displays the last 200 posts regardless of the board or category. Nothing fancy, they are numbered and should have some options beneath each post like reply, reply with quote and report to moderator. Here you have an additional [printscreen](https://imgur.com/9dvLaXT).
And that page is available to anyone. You should just have a toggle/checkbox in the settings menu if you want the link to the page to be displayed, or could write the url yourself if you know it :)) 

I guess they were named the same because that page would help out mostly users with that role...

**Comment by Rizzrack09** [comment]
I'm sure you guys have it but I'll just leave the link here for the bitcointalk patrol page
https://bitcointalk.org/index.php?action=recent;patrol
