### ISSUE TITLE
[bug] posts - posts in profile - activity

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#722]
Seems alanst has 1 post, however displays Number of Posts as being 3
![post-activity](https://user-images.githubusercontent.com/51131936/69331670-dbf54e80-0c5d-11ea-88b3-bfc616735732.JPG)
Also activity does not calibrate with posts.
If one of your posts is deleted => one post less, one activity less ! 
Users cannot have more activity then posts. 

Post: https://coinbistro.com/threads/6wU9zwtWT_KyYkVJa-QuAQ/posts

**Comment by akinsey** [comment]
Noted! This will be fixed when we redo the activity module

**Comment by akinsey** [comment]
Dupe issue closing for now, this will be resolved when we update activity!
