### ISSUE TITLE
Local storage should be cleared when session is invalidated upon server restart

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#725]
Upon restart, even though I'm logged out, I still have all the local storage data of the user who was logged in. (Ubuntu)

**Comment by unenglishable** [comment]
should check if this is a ubuntu server-side or client-side problem..  our production builds run on linux, and i haven't noticed anything like this.

i recommend trying different browsers etc.  this will help narrow down where the issue is coming from 👍
