### ISSUE TITLE
Posts with same post position when purging and recreating posts in a thread

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#734]
I was somehow able to get two posts with position #25. Upon deleting both and creating a new posts I get duplicate #24, etc...

Not sure how to recreate. I'd assume creating posts up to the page limit the purging and creating more posts

**Comment by unenglishable** [comment]
to recreate:

add some posts to a thread

as an admin, hide some posts.  then, purge a post

the next post written will be at a higher number

**Comment by akinsey** [comment]
just hiding the post appears to throw the count off. I'm assuming this is something to do with the `deleted` flag on posts
