### ISSUE TITLE
[feature] Enable/disable self modetared threads in board

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#750]
There are some boards on bitcointalk (Meta for example) where it is not possible to make a self moderated thread.
There should be an option to allow or not self-mod threads when creating the board, or edit that later on

Post: https://coinbistro.com/threads/36LUKBFxQ82XpQDlUXm4mA/posts?page=1#JgS-n25oQ2qD0ZZgu9H6Bw

**Comment by akinsey** [comment]
fixed in https://github.com/epochtalk/epochtalk/pull/862
