### ISSUE TITLE
[bug] Modifications for the Reset password email

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#752]
When admin resets user's password or when the actual user clicks on forgot my password it sends an email that should contain password reset link. There is no URL in the email. 
Not sure if email server not configured on Coinbistro or actually a bug.
The word "Reset" is decorated as a link, with blue color but is not clickable. Not a link, looks just like a placeholder for the moment.
![pass reset email](https://user-images.githubusercontent.com/51131936/73184186-b6d10080-4124-11ea-9b84-9b7e0eeb8743.JPG)

Post: https://coinbistro.com/threads/0qdEe7ylSWaACpDJBE3LMA/posts

**Comment by akinsey** [comment]
Hmm this appears to be working for me, can you confirm this is still an issue? @Rizzrack09

**Comment by Rizzrack09** [comment]
This is from the raw version of the email
`<strong>Password</strong>:<a href=3D"https:&#x2F;&#x2F;coinbistro.=
com&#x2F;reset&#x2F;Coin_BoT&#x2F;[reset_token_code]"= >Reset</a>`

Seems the quoted-printable format is not being decoded properly. &#x2F not read as /
Weird you say it works for you tho. Tried with Mozilla, Chrome (desktop and mobile) and Opera.
I tried to reconstruct the link manually and it worked. 

![inspect-element-email](https://user-images.githubusercontent.com/51131936/75247957-cbfc8600-57db-11ea-960c-6c57c167bf9a.JPG)
Inspect element does not detect any URL link

**Comment by Rizzrack09** [comment]
After some more test seems email client was blocking the URL (Yahoo)
For cases in which the email client blocks the reset link, it would be nice to also offer the URL somewhere near the email footer "If you cannot click copy this URL in a new tab" or something similar. 
The email should also contain the valability period of the reset token "valid for 1-2-3 hours" and also a disclaimer that if you did not use the forgot password function please ignore email.
