### ISSUE TITLE
[feature] secret question

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#753]
More info in the post: https://coinbistro.com/threads/OuiztfyhSvSb5b2xH8bkVA/posts

**Comment by theymos** [comment]
Secret questions are insecure, and should not be supported. They basically only exist in bitcointalk.org for backward compatibility.

**Comment by Rizzrack09** [comment]
Wasn't too sure myself if it would be a feature worth migrating. Added it here to be debated. Glad to see it got solved quickly :))
