### ISSUE TITLE
[bug] Sorting in Member Search is buggy

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#755]
When you sort users in the Member Search (ept-users) by something other than username there are some issues.
This is how the first 2 pages look when sorting by Posts (user "EFS" is in both pages, and because of that someone else was left out):
![pagination_byPosts](https://user-images.githubusercontent.com/51131936/73282248-f289ca00-41f9-11ea-9d71-1525a22877bd.JPG)
This is how the first 2 pages look when sorting by Roles (a lot more bugs):
![pagination_byRole](https://user-images.githubusercontent.com/51131936/73282270-fb7a9b80-41f9-11ea-9eb0-9e1fe603d122.JPG)
It seems the User Management screen in the Admin Panel has no issues with sorting... at least from what I was able to test

Post: https://coinbistro.com/threads/NDItutaARm-kFt_YRKIqMA/posts

**Comment by akinsey** [comment]
This should be resolved, if you still have issues let me know!
