### ISSUE TITLE
[bug] pagination issue for new posts

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#761]
I made a few test posts after the last release and they were not appended to the bottom of the post list.
They were moved between some older posts and received the same post number. Posts 49 and 50. (now there are 2 of each)
https://coinbistro.com/threads/I4GzlgyAQFuRznEUOieuaA/posts?start=49#5p_Peb8CSWaNlAHW2tXGyA
https://coinbistro.com/threads/I4GzlgyAQFuRznEUOieuaA/posts?start=50#XW1dGsjvSg-IqFa4ZxZpEw

After these 2 posts the others behaved correctly (not able to replicate yet)
There are some older bugs like this here: https://coinbistro.com/threads/I4GzlgyAQFuRznEUOieuaA/posts?start=12#2VtWechsTbKmwrDJm8pdDA
Post number 12-15-15-16

Tried to delete, hide, purge some posts but could not replicate it yet.
They were the last 2 posts made on the page. After that the next post went on the next page and behaved as expected from then on.

Will edit when I have more info

**Comment by akinsey** [comment]
Just curious was the thread you're having issues with created before we applied the update?

**Comment by Rizzrack09** [comment]
I noticed the bug in an old thread.
I thought about that and made a new one also. Same thing happens in the new thread.
This is a link for post no. 4 in the new thread: https://coinbistro.com/threads/0ikKhHejRWmWWV3R8l6EgA/posts?start=4#hDP5_BQ-SM6-lXS_yEXDaQ
The post is question is highlighted as you would expect but takes you to the top of the page, not at that post height

**Comment by Rizzrack09** [comment]
Sorry, was answering here but thinking about another issue :))

This happened in an old thread.
Created a new thread where I will test it further a bit and if can't replicate will assume it is solved :P

**Comment by akinsey** [comment]
Awesome! Yeah I believe it was the way we were hiding posts before causing the post counts to get messed up. Fixing this only fixed new threads not old ones!

**Comment by Rizzrack09** [comment]
so far so good!
By the looks of it, issue is solved
Well played sir !
