### ISSUE TITLE
[bug] post duplicate on double click

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#768]
If you click twice on "Post reply" it duplicates the post.
If you are too fast you get stopped by posting rate limit, but still can manage to do that.
Clicking the button should send only one request. 
Would suggest something similar to modals. After click changes the state into Posting or something like that (just a suggestion)

Thanks suchmoon for pointing it out

**Comment by akinsey** [comment]
Good catch I'll take a look
