### ISSUE TITLE
[feature] add user to ignore list from settings page

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#775]
Would be helpful to also have a manual way to add users to ignore list
![d60f79e819cabb44579b442bb3040035aa8defeb](https://user-images.githubusercontent.com/51131936/75342166-881e8500-589e-11ea-8a0e-4b085a9e9849.jpg)
A button "Find user" and to add him to the ignore list.
Better than finding him in member search, go on one of his posts and then click the ignore button

Post: https://coinbistro.com/threads/Rg8Qd5HcRU-sk447JUI9Dg/posts

**Comment by akinsey** [comment]
Sounds good!

**Comment by akinsey** [comment]
This should be resolved with the newbie restrictions merge!
