### ISSUE TITLE
[modification] Avatars should be reclangle

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#777]
Avatars should be rectangle and 120x80 px (or if slightly bigger should keep the same proportion 3:2)
Users use their avatar as ad space and round ads are harder to create. Also would mean they get to keep their current avatar or will not look weird pre migration

Post: https://coinbistro.com/threads/3Zr8PXK6RA69yEJcQwi5mg/posts

**Comment by akinsey** [comment]
I mentioned this to our designer!

**Comment by CyrusV5** [comment]
Generally speaking, IMO round avatars make more sense when you use them for faces or busts, like in a social media website, but probably not so much in forums.

**Comment by ruesato** [comment]
@akinsey whenever you have a chance, can you add a control allowing the admin to toggle rectangular vs round user avatars?

When the `rect` class is added to the `.post-user` element on `post-data.html`, the avatars will become rectangular with a 3:2 aspect ratio.

**Comment by akinsey** [comment]
This should be fixed in the UI Branch!
