### ISSUE TITLE
[bug] hidden posts

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#787]
As Admin I cannot see hidden posts by users. 
![hidden post](https://user-images.githubusercontent.com/51131936/76212498-492eee80-6211-11ea-8fe0-860cd16e5d72.jpg)

**Comment by akinsey** [comment]
@Rizzrack09 are you able to reproduce this? I tried in my local install of master and the hidden post is visible to me as admin:

![https://i.imgur.com/S0oASql.png](https://i.imgur.com/S0oASql.png)

**Comment by Rizzrack09** [comment]
Can you see post 3 ?
https://coinbistro.com/threads/bDsW5ugzQr2zbm-E7JmYTw/posts

Could have been solved after #764 but Coinbistro not updated to 1.11.2, not sure what to say...

**Comment by CyrusV5** [comment]
FWIW, I can see post 3 as Super Admin.

**Comment by Rizzrack09** [comment]
That is very strange.
For me it's hidden and cannot unhide it. It's not clickable
This is what I see
![lockedpost](https://user-images.githubusercontent.com/51131936/76848978-3d64ad00-684d-11ea-996a-90631339241f.jpg)

**Comment by akinsey** [comment]
I found the issue i think guys, It's a bug with @Rizzrack09  being both a patroller and super admin, I'll take a look.

**Comment by Rizzrack09** [comment]
when I removed my patroller role I was able to see the post correctly. Seems that was the issue ...
