### ISSUE TITLE
[feature] lock post info

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#792]
Might be a good idea to identify who locked a certain post. Was it OP in selfmod, was it mod?
Best case scenario would be like edit... hover on the lock icon and the tooltip would display smth like "Locked by mod. Unlock post" "Locked by OP. Unlock post" or even "Locked by {{username}}. Unlock post"
Penny for your thoughts :)

**Comment by CyrusV5** [comment]
IMO Locked by OP / Locked by mod would be acceptable, I wouldn't add the mod's username though.

**Comment by akinsey** [comment]
We are currently showing who edited a post, is lock any different?

**Comment by CyrusV5** [comment]
If you already have the data, feel free to treat it the same way, ie: show user. I don't see any downsides and the extra info is useful. Right now, the user who locked it is not being shown on Bitcointalk.

**Comment by akinsey** [comment]
https://github.com/epochtalk/epochtalk/pull/868
