### ISSUE TITLE
[bug] registration "email is taken" error on invalid email addresses

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk#794]
my guess is that "email is taken" shows up when typing an invalid email
recent hapi/joi updates to validations put stricter guidelines on email address.

solution:  a different message should be shown when addresses are taken vs when addresses are invalid

**Comment by akinsey** [comment]
boka, i think we decided in the past that the email doesnt need to be valid if you want to remain anonymous and the forum isnt set to verify accounts. The solution was to set the joi validation, back to allowing string and not checking if the payload is a valid email. Everything seems to be working the way it was before now
