### ISSUE TITLE
[refactor](ui-refactor-2020) Thread list view is inconsistent with Posts view

### ISSUE THREAD

**Issue by ruesato** [epochtalk/epochtalk#804]
Thread list view design should be consistent with Posts view
- footer
- sidebar sticky
- header

**Comment by ruesato** [comment]
@akinsey when you have a chance, can you take a look at the Thread list view and verify that it looks good in desktop and mobile?

**Comment by akinsey** [comment]
sounds good

**Comment by akinsey** [comment]
Looks good on mobile and desktop, as far as I can tell!

**Comment by ruesato** [comment]
Thank you, closing issue
