### ISSUE TITLE
[bug](ui-refactor-2020) Patrol view does not follow grid

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#807]
Patrol view does not respect new grid system

**Comment by ruesato** [comment]
@akinsey where is the Patrol view?

**Comment by CyrusV5** [comment]
It should probably be in the header User dropdown menu > Patrol.

**Comment by akinsey** [comment]
@ruesato you have to either have the patoller role, or go into your user forum setting and toggle the show patrol view setting. Once you do that it will show up in your dropdown.

**Comment by ruesato** [comment]
should be fixed in commit 5a4a65469bf64389d8d3d855eb93716b35830e8d

**Comment by ruesato** [comment]
Closing
