### ISSUE TITLE
[bug](ui-refactor-2020) Patrol view still using old editor

### ISSUE THREAD

**Issue by ruesato** [epochtalk/epochtalk#811]
When I click the "Edit Post" button in the Patrol view, the original post editor UI appears. Can we move this to the new editor component?
![image](https://user-images.githubusercontent.com/1944770/78769182-b1641380-7928-11ea-9d74-586b3c3b6958.png)

**Comment by akinsey** [comment]
Fixed in 8dc5e2df63ede8a6640ebdd6d839738398adaae9
