### ISSUE TITLE
Update version of Angular

### ISSUE THREAD

**Issue by shadowfox87** [epochtalk/epochtalk#814]
This forum is great as it's trying to be the next gen. However, it seems it is using AngularJS v1.7.9 and JQuery shows this.  Angular is up to version 9 now. Is there any plans to update this?

**Comment by Rizzrack09** [comment]
Angular is up to version 9 (even 10 beta): https://github.com/angular/angular/releases
AngularJS is up to 1.7.9: https://github.com/angular/angular.js/releases

Considering it uses AngularJS ... it is up to date :)
Angular and AngularJS are not the same thing.

**Comment by akinsey** [comment]
Thank you @Rizzrack09! As mentioned above we are on the latest version of AngularJS. Once the product reaches a more stable point, we may upgrade to the typescript version of Angular, but at this point and time it does not make sense for us to upgrade. 

Thank you!
