### ISSUE TITLE
[modification] allow symbols and space in usernames

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#819]
For the moment epochtalk accepts only a-z / A-Z / - / _ / . for usernames.
It should accept most of the UTF-8 char list (latin, greek, arabic, chineese, cyrillic, regular symbols etc)

Not sure how many of then are currently allowed on bitcointalk but there are all sorts of usernames...
[¤ ¥ § © ® ³ µ ¶ ¸ ¹ ¼ ½ ¾](https://bitcointalk.org/index.php?action=profile;u=370761) (used to be very permissive ... it changed now but not sure to what extent)
But the regular ones you find on a US keyboard for sure.
Might need to double check with theymos for the full updated list tbh

Also regarding spaces ... only 1 space between characters.

**Comment by akinsey** [comment]
I believe we brought this up in a past bct meeting, I think we agreed we would grandfather in old user's usernames, but new ones would be restricted (I believe there are security concerns when allowing a large assortment so special characters).

Not set in stone, so open to discussion @Rizzrack09

**Comment by CyrusV5** [comment]
Sounds good to me, plus it can be revised later if needed.

**Comment by akinsey** [comment]
Closing for now will revisit later if necessary
