### ISSUE TITLE
bug: Cannot add web site to user profile

### ISSUE THREAD

**Issue by ruesato** [epochtalk/epochtalk#822]
UI displays a "Profile could not be updated" error when trying to add a web site to a user profile.

1. go to user profile page
1. click Edit Profile
1. enter a url in the web site field
1. click "Save"
1. note that an error message appears at the top of the page, and the url was not saved to the profile

The following error appears in the console:
`angular.js:13565 PUT http://localhost:8080/api/users/juBtII9gQb-BrGIdd397tQ 400 (Bad Request)`

**Comment by Rizzrack09** [comment]
I would assume it has to do with regex url permissions
https://github.com/epochtalk/epochtalk/blob/3dd8b51fc699ea2c0d1c5e13233b57b6f155bee9/server/plugins/sanitizer/index.js#L37

Only accepts URLs starting with https, http, fpt, mailto

If you try www.website.com or even website.com it would not work. At least this is what I experience.
Might need to change that to also work with www. IMO

**Comment by akinsey** [comment]
Fixed it! Thanks @Rizzrack09, it was our joi validation being too strict and requiring the protocol to be present in the url. I updated it to use a more lax regex to check the profile url!

**Comment by Rizzrack09** [comment]
@akinsey for trust feedback the regex is just as restrictive
https://github.com/epochtalk/epochtalk/blob/ffe2e9f8273562ddd0108660861bd4e89249c084/modules/bct-trust/client/trust.controller.js#L16
Maybe the www. could also be allowed there ? 

![refference](https://user-images.githubusercontent.com/51131936/81187998-743d8080-8fbd-11ea-9649-b6eba52244ca.jpg)
