### ISSUE TITLE
[bug - mobile] New message view 

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#835]
When the message modal opens it is aligned to bottom and cannot see the _To:_  and _Subject:_ fields.
When the phone keyboard opens takes me below the field where I am typing and it's not a pleasant feeling typing blind 
It should focus on modal as swiping and and down change the view under the modal
<img src="https://user-images.githubusercontent.com/51131936/83139301-d0934c00-a0f4-11ea-8a71-98f3746ca109.jpeg"  width="250" height="517">

**Comment by akinsey** [comment]
Thanks for catching this!
