### ISSUE TITLE
[feature - mobile] Message view UI/UX proposal for mobile

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#836]
On the messages page there is a conversation list and message list. If the list of conversations would be too long users would need to scroll a lot to get to the message they wanted.
How about split them into 2 pages for mobile.
On messages you would have just the conversations list with search function.
Once you click on a conversation you are taken to the page with the messages. 
More or less similar to other messaging apps like WhatsApp or Telegram 
Message page should also have search function and a possibility to switch between newest messages top or newest messages bottom

**Comment by akinsey** [comment]
We might be able to achieve this with css, thank you for the input! @ruesato is still working on the mobile design, so some of the features might not be 100%. Thanks for catching these and pointing them out~

**Comment by Rizzrack09** [comment]
Should work with CSS and seems more straightforward and possibly a bit faster. Cool !

**Comment by ruesato** [comment]
@akinsey can I get your eyes on this?
