### ISSUE TITLE
[bug] website in profile link

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#842]
#824 - does this work for you guys ? 
On my end if I add www.epochtalk.org in the website field it gives me the following link
https://domain_name/www.epochtalk.org
It treats it as an internal link

**Comment by akinsey** [comment]
hmm this is why it was strict prior to the recent change. It takes what was entered and dumps it into an html anchor tag. Links starting with www. are not valid in an anchor tags href property.

I don't know if its worth it, but we will probably either have to detect if they don't have the http prefix then attach it, or revert back to the old regex. If we attach it though we dont know if the site supports https or just http

**Comment by Rizzrack09** [comment]
> If we attach it though we dont know if the site supports https or just http

I guess most websites would have a redirect to https if available, so might be fine with just http imo

**Comment by akinsey** [comment]
Sounds good, Ill take care of it
