### ISSUE TITLE
[feature] column sorting in board view

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#856]
Thread created_at moved to it's own column
And also add clickable column header sorting mainly for VIEWS, REPLIES, LAST POST (because the default sorting on some boards was changed on bitcointalk #642 ) and the future STARTED ON (or what ever the name would be). I doubt anyone would order the threads alphabetically by name but might add filter on that just for consistency ... or not :raccoon:

**Comment by akinsey** [comment]
Thanks for the feature request! What would be the difference between created_at and started_on?

**Comment by akinsey** [comment]
abd7a7b47f153f7c1c1d851406fdaf7ad5165d46 added!
