### ISSUE TITLE
ux: bug with header remaining hidden after view change

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#863]
Sometimes when you scroll a bit down untill the header disappears and then try to click on a board the header does not reappear on the board view. Same behavior if you click on a thread. Problem is when you click on a thread with a single small post because there is no way to scroll and make the header appear.
![coinbistro-main-view](https://user-images.githubusercontent.com/51131936/85930216-442aa380-b8c3-11ea-8389-e1f114c297e8.png)
![coinbistro-board-view](https://user-images.githubusercontent.com/51131936/85930257-953a9780-b8c3-11ea-8839-48f8473db319.png)
![coinbistro-thread-view](https://user-images.githubusercontent.com/51131936/85930219-4a208480-b8c3-11ea-9021-0a4b87450f9c.png)

**Comment by akinsey** [comment]
Thank you for the report ill look into this!
