### ISSUE TITLE
[bug] issues with slugs

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#890]
1. (asterix symbol) *  in thread title gives out an error and thread cannot be posted
`{"statusCode":400,"error":"Bad Request","message":"Invalid request payload input"}`
2. ~ symbol is doubled in slug. So ~ turns into ~~.
When on the website the transition is made by id so the link works. But if you click on that link from an external source it gives a 404 . The links works just need to remove one of the ~ symbols
https://coinbistro.com/threads/slug-test-~~/posts (404 error)
https://coinbistro.com/threads/slug-test-~/posts (ok)
![slugs](https://user-images.githubusercontent.com/51131936/91555035-e9500f80-e938-11ea-9cb7-cd10bec5984e.png)
3. cannot start a thread if in the title I write in chinese, hebrew, japanese, arabic, bengali, persian, thai etc These are all on bitcointalk. Might have missed a few ...
`{"statusCode":400,"error":"Bad Request","message":"Invalid request payload input"}`
4. after I delete (purge) a thread it does not take me back to the board. It remains on the same url and gives out a 503
`The following parameter values are not valid for state 'threads.data': [boardSlug:undefined]` because the url is not valid anymore

**Comment by akinsey** [comment]
Super useful info thank you! I will work on fixing these!

**Comment by Rizzrack09** [comment]
One of our users on Coinbistro found another weird bug.
Seems the BBCode parser has issues when these two symbols are in the thread title ' (single quote) and ! (exclamation mark)
Double quote " works

If I make a posts where I insert a hyperlink linking to any post in a thread that has those two symbols in the title like this `[url=https://coinbistro.com/threads/url-posts-!/posts?start=1#3XpR5uFRTHyEzKNOIWUeog]This post looks weird[/url]` it just displays `https://coinbistro.com/#`

See below post as example: https://coinbistro.com/threads/url-post-with-symbols-'-!/posts?page=1#0zNjclbxSqidBILHj5HxOg

**Comment by Rizzrack09** [comment]
Symbol in the title break quote link. Pretty much any symbol from what I can tell...
![Screenshot from 2020-09-17 14-53-04](https://user-images.githubusercontent.com/51131936/93466865-90e7ae80-f8f5-11ea-8fab-31d3045432fc.png)
https://coinbistro.com/threads/2565ad38-0458-449f-a225-b3d0e3b89c44/posts?start=5#pX-jXOs4SAaENY3KWvlrsg
