### ISSUE TITLE
Trust views are broken in Ui-refactor

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#901]
@ruesato

**Comment by akinsey** [comment]
If you click "View Trust Feedback" in a users profile, this view is not formatted for the redesign

**Comment by akinsey** [comment]
Also if you click "Edit Trust List" from the previous view mentioned, this view is also broken

**Comment by ruesato** [comment]
@akinsey I might circle back to improve the layout of the Trust Settings view. May need some guidance from you at that point.

**Comment by ruesato** [comment]
Closing for now, will improve view in future refactor
