### ISSUE TITLE
[bug] issues with quotes

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#912]
Besides the [symbols in the thread title](https://github.com/epochtalk/epochtalk/issues/890#issuecomment-694181102) seems that unclosed tags also break quotes... so decided to make a separate issue about them after all.
You can see here: https://coinbistro.com/threads/2565ad38-0458-449f-a225-b3d0e3b89c44/posts?start=9#CoSQI6xeQVSQQlTP0NahcA
If tags are not closed [b] [/b] or [br] [/br] ([hr] tag works) quote is broken.

**Comment by akinsey** [comment]
b is expect as it requires a closing, our current parser requires complete tags, but we will be rewriting/replacing the bbcode editor to be 1 to 1 with bitcointalk. For now I've fixed the self closing tags br and hr.
