### ISSUE TITLE
UX: on the UI-refactor-2020 branch some options in user settings are doubled

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#915]
@ruesato some settings appear two times in [user settings page from UI-refactor branch](https://coinbistro.com/settings)
User Message Settings, Mentions and Timezone Offset.
So pretty much from line [25](https://github.com/epochtalk/epochtalk/blob/cda113884effa3372bffd7ad097a14f8447f20d9/modules/ept-users/client/settings/settings.html#L25) to line 35 should be removed (from what I can tell)
Post: https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=25#ma1sK0p3RXWyBBvIjQMPRg

**Comment by ruesato** [comment]
Fixed. Closing issue.
