### ISSUE TITLE
UX: Send Reply button hidden under footer when editor expanded

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#916]
User also made a _gif_ with the issue
See here: https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=27#eGd0QxmfQxmDJ08jMOHseg

Might be better to hide the "Post Reply" button when editor expanded and add margin-top/bottom so editor fits between header and footer

**Comment by akinsey** [comment]
https://i.imgur.com/OSO1LsX.gif

**Comment by akinsey** [comment]
fixed in 059280736dcbe2aa5b44b6cab25beafecd7abac6
