### ISSUE TITLE
[ui-refactor-2020] Login view is not styled

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#921]
SSO login button is not styled in the login view, inputs are still old style, should these match the modal login inputs?

**Comment by ruesato** [comment]
@akinsey thats strange... this is what I see on the `ui-refactor-2020` branch

![image](https://user-images.githubusercontent.com/1944770/94315846-07506600-ff1f-11ea-8344-6192e4b308cb.png)

**Comment by akinsey** [comment]
It's the view if you for example are logged into the admin panel, or if the forum is private and you restart the server, you become deauthenticated and it takes you to a view with the same login form, except its a view not a modal. Should be in ept-frontend client layout folder. If you try to hit a route that requires auth, before you login you should see the view
