### ISSUE TITLE
UX: extra hr lines on profile page

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#926]
viewing the profile page as guest hr lines are still visible when options are hidden
![Screenshot from 2020-06-25 19-17-57](https://user-images.githubusercontent.com/51131936/85758688-3a653c80-b719-11ea-9a15-604830d03c29.png)

**Comment by ruesato** [comment]
@Rizzrack09 this should be fixed in the latest build. Can you confirm and close this issue?

**Comment by Rizzrack09** [comment]
solved
