### ISSUE TITLE
UX: ONLY UPPERCASE TOOLTIPS for info icon

### ISSUE THREAD

**Issue by Rizzrack09** [epochtalk/epochtalk#927]
In the admin panel all info icons have uppercase text which is not very pleasant 
![Screenshot from 2020-09-28 17-59-20](https://user-images.githubusercontent.com/51131936/94449257-91fdc300-01b4-11eb-9461-504727086696.png)

**Comment by ruesato** [comment]
Agreed, that is definitely unpleasant ☹️ 

Fixed in commit feaed153cba154f82034ba23cbf45bf143cc125f
