### ISSUE TITLE
[BUG] Editing profile clears signature

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#929]
https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=45#FYP1_gZYSP6V9cMQtWTduQ

**Comment by akinsey** [comment]
![https://i.imgur.com/Cp1lWxB.gif](https://i.imgur.com/Cp1lWxB.gif)

**Comment by Rizzrack09** [comment]
Also making changes in "settings/ignore boards" has the same issue. After that signature dissappears and need to re-save it in order to be displayed again.

**Comment by akinsey** [comment]
ill take a look! thank you!
