### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by incorpusyehtee** [epochtalk/epochtalk#94]
I have a feeling there are some steps before running `node cli/index.js --create`. How should the database be configured? Currently I either get an opentableparser error (if I create my own epochtalk database) or an auth_failed error (even if postgresql is set to trust local socket connections/local loopback connections).

Any help would be appreciated.

**Comment by wangbus** [comment]
Apologies, it's broken. I'll have this fixed up soon.

**Comment by taesup** [comment]
Pretty sure this has been fixed by now. Closing this issue.
