### ISSUE TITLE
[Bug] Links on topics which were started by user don't work in profile

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#960]
When I try to go to topics which were started by user from the tab "Threads by ...", I get error #503.

GIF with this bug:

![Threads by user bug](https://user-images.githubusercontent.com/72157778/95049686-ec39df00-06f2-11eb-86a3-681bdb568927.gif)

**Comment by akinsey** [comment]
Thank you! I will look into this!
