### ISSUE TITLE
[Bug] issue with uploading images less than 1 kb

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#984]
When I try to upload pictures less than 1 kb by using the "Upload Images" function on [Coinbistro forum](https://coinbistro.com/), the following error message appears:

> Image upload failed for: {File Name}. Error: undefined

Although almost the same picture which equal to 1 kb can be uploaded to the forum.

Image №1, 1023 bytes <-- Error message appears
![coinbistro_small_image_in_avatar_test(11)](https://user-images.githubusercontent.com/72157778/95566611-769f7d00-0a2a-11eb-9929-dfeb444a2e34.png)

Image №2, 1024 bytes <-- Successful upload
![coinbistro_small_image_in_avatar_test(12)](https://user-images.githubusercontent.com/72157778/95566630-7d2df480-0a2a-11eb-8b49-974ae1f95765.png)

**Comment by akinsey** [comment]
This might be due to our amazon s3 policy well take a look
