### ISSUE TITLE
[Bug] issue with disappearing "Report" buttons

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#988]
When you press the "Report" button, but don't send anything, then this button disappears from the post and reappears again when the page is refreshed.

The GIF below with the described problem.

![disappearing report button](https://user-images.githubusercontent.com/72157778/95754743-29cad900-0cac-11eb-8080-261c16e2cb46.gif)

**Comment by Rizzrack09** [comment]
Seems just the "Report user's post" option disappears. The "report user" option still remains. It does not show in the gif because he already reported that user before (for testing purposes)

**Comment by Vele0r** [comment]
Yes, the error with the button disappearing is probably due to the fact that I reported on this user before.
However, I would like to point out that when I click on the Report button for another user, I see the two options at first: 1) report the user and 2) report the user's post. But after canceling the Report window and clicking the same "Report" button again, the only one option is available to me.

![report issue](https://user-images.githubusercontent.com/72157778/95767472-7965d080-0cbd-11eb-98e5-8784c8fd0a37.gif)
