### ISSUE TITLE
[Bug] search issue with hidden posts

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#991]
Forum search finds keywords in hidden posts.

> **Rizzrack:** Generally it should ignore hidden posts, unless you search for your post  or you are a mod/admin and you can view user hidden posts to begin with. Currently it shows everything. If you search "Tom&Jerry" you will get a search result even though I set that post to hidden.
[Post # 67](https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=67#fnTJsIVDTAGPMoOnKLvwRw)

**Comment by akinsey** [comment]
Thank you this is a good find
