### ISSUE TITLE
[Bug] the first character in a line after quoted text is disappearing

### ISSUE THREAD

**Issue by Vele0r** [epochtalk/epochtalk#993]
Look at the GIF below with this bug

![issue with first character in a line after quote](https://user-images.githubusercontent.com/72157778/95814927-486cb680-0d24-11eb-894b-6e5b3b8b5e6c.gif)

**Comment by Vele0r** [comment]
Some old posts also lost the first character in the first line after the quote.

![missing_letter](https://user-images.githubusercontent.com/72157778/95826143-8ecd1000-0d3a-11eb-8b6f-69e3b93b82ee.png)

Link to the post: https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=3#0yFPPjsCTQ-82DWrIcdDVw

**Comment by Rizzrack09** [comment]
Seems it started doing this again: https://coinbistro.com/threads/aa2c7b02-8522-4213-a7da-c050b2b1d570/posts?start=98#e09TjDnTR9qHNRqCHSlI8A
